-- =====================================================
-- S008: Position classifiers
-- Source: /docs/lavozim_klassifikatorlar_2026.xlsx
-- =====================================================
-- Note: University activity statuses are NOT inserted here.
-- V012 university_lifecycle uses CHECK constraint for event types.
-- Old hemishe_h_university_activity_status table is managed by old-hemis only.

-- 1. Position types (14 ta)
INSERT INTO position_type (code, name, name_ru, name_en) VALUES
  ('10', 'Boshqa', '', ''),
  ('11', 'Administrativ-boshqaruv xodim', '', ''),
  ('12', 'Professor-o''qituvchi xodimlar', '', ''),
  ('13', 'O''quv-yordamchi va texnik xodim', '', ''),
  ('14', 'Xizmat ko''rsatuvchi xodim', '', ''),
  ('15', 'Rektorat rahbar xodimlari', '', ''),
  ('16', 'Rektorat boshqaruv-texnik xodimlari', '', ''),
  ('17', 'Ta''lim va tarbiyaviy faoliyat xodimlari', '', ''),
  ('18', 'Moliyaviy-iqtisodiy faoliyat xodimlari', '', ''),
  ('19', 'Raqamlashtirish faoliyati xodimlari', '', ''),
  ('20', 'Kutubxona, muzey va nashriyot xodimlari', '', ''),
  ('21', 'Texnik foydalanish va xo''jalik xodimlari', '', ''),
  ('22', 'Kadrlar va ish yuritish xodimlari', '', ''),
  ('23', 'Tibbiyot, biologiya va san''at xodimlari', '', '')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- 3. Positions (227 ta — to'g'ridan-to'g'ri Excel dan)
INSERT INTO position (code, name, name_ru, name_en, type_code) VALUES
  ('47', 'Boshqarma boshlig''i', '', '', '11'),
  ('48', 'Boshqarma boshlig''i muovini', '', '', '11'),
  ('19', 'Markaz boshlig‘i', '', '', '11'),
  ('17', 'Bo‘lim boshlig‘i', '', '', '11'),
  ('35', 'Bosh mutaxassis', '', '', '11'),
  ('54', 'Yetakchi mutaxassis', '', '', '11'),
  ('36', 'Mutaxassis', '', '', '11'),
  ('101', 'Ish yurituvchi', '', '', '11'),
  ('55', 'Marketolog', '', '', '11'),
  ('120', 'Muhandis', '', '', '11'),
  ('189', 'Yetakchi muhandis', '', '', '11'),
  ('180', '1-toifali muhandis', '', '', '11'),
  ('177', '2-toifali muhandis', '', '', '11'),
  ('43', 'Texnik', '', '', '11'),
  ('181', '1-toifali texnik', '', '', '11'),
  ('179', '2-toifali texnik', '', '', '11'),
  ('29', 'O',           '', '', '11'),  -- TODO: bu nom manba DB da 'O' (buzilgan). To'g'ri nom universitetlar bilan tekshirilishi kerak
  ('16', 'Kafedra mudiri', '', '', '12'),
  ('15', 'Professor', '', '', '12'),
  ('14', 'Dotsent', '', '', '12'),
  ('13', 'Katta o‘qituvchi', '', '', '12'),
  ('12', 'Assistent', '', '', '12'),
  ('11', 'Stajer-o‘qituvchi', '', '', '12'),
  ('20', 'Rektor', '', '', '15'),
  ('46', 'Birinchi prorektor', '', '', '15'),
  ('22', 'O‘quv ishlari bo‘yicha birinchi prorektor', '', '', '15'),
  ('153', 'O''quv ishlar bo''yicha prorektor', '', '', '15'),
  ('23', 'Yoshlar bilan ishlash bo‘yicha prorektor', '', '', '15'),
  ('28', 'Axborot texnologiyalari bo''yicha prorektor', '', '', '15'),
  ('33', 'Davolash ishlari bo''yicha prorektor', '', '', '15'),
  ('183', 'Fundamental fanlar bo’yicha prorektor', '', '', '15'),
  ('21', 'Ilmiy ishlar va innovatsiyalar bo‘yicha prorektor', '', '', '15'),
  ('233', 'Ilmiy va uslubiy ishlar bo‘yicha prorektor', '', '', '15'),
  ('117', 'Moliya-iqtisod ishlari bo‘yicha filial direktori o‘rinbosari', '', '', '15'),
  ('24', 'Moliya-iqtisod ishlari bo‘yicha prorektor', '', '', '15'),
  ('221', 'Strategik rivojlantirish bo‘yicha birinchi prorektor', '', '', '15'),
  ('65', 'Transformatsiya ishlariga mas''ul bo''lgan prorektor', '', '', '15'),
  ('32', 'Xalqaro hamkorlik bo''yicha prorektor', '', '', '15'),
  ('31', 'Direktor', '', '', '15'),
  ('90', 'Filial direktori', '', '', '15'),
  ('241', 'Ijrochi direktor', '', '', '15'),
  ('84', 'Direktor o‘rinbosari', '', '', '15'),
  ('125', 'O‘quv ishlari bo‘yicha filial direktori o‘rinbosari', '', '', '15'),
  ('156', 'Yoshlar masalalari va ma’naviy-ma’rifiy ishlar bo‘yicha filial direktori o‘rinbosari', '', '', '15'),
  ('147', 'Xalqaro hamkorlik bo‘yicha filial direktori o‘rinbosari', '', '', '15'),
  ('98', 'Ilmiy ishlar va innovatsiyalar bo‘yicha filial direktori o‘rinbosari', '', '', '15'),
  ('164', 'Rektor maslahatchisi', '', '', '16'),
  ('49', 'Rektor yordamchisi', '', '', '16'),
  ('104', 'Ishlar boshqarmasi boshlig‘i', '', '', '16'),
  ('81', 'Bosh muhandis', '', '', '16'),
  ('79', 'Bosh energetik', '', '', '16'),
  ('99', 'Ilmiy kengashning ilmiy kotibi', '', '', '16'),
  ('63', 'Kengash kotibi', '', '', '16'),
  ('184', 'Maslahatchi (Matbuot kotibi)', '', '', '16'),
  ('38', 'Matbuot kotibi', '', '', '16'),
  ('106', 'Katta yuriskonsult', '', '', '16'),
  ('52', 'Yuriskonsult', '', '', '16'),
  ('182', 'Bosh huquqiy maslahatchi', '', '', '16'),
  ('68', 'Ish yurutuvchi kotib', '', '', '16'),
  ('112', 'Kotib-ish yurituvchi', '', '', '16'),
  ('50', 'Bosh auditor', '', '', '16'),
  ('131', 'Pasportist', '', '', '16'),
  ('25', 'Dekan', '', '', '17'),
  ('26', 'Dekan muovini', '', '', '17'),
  ('138', 'Sirtqi (maxsus sirtqi) ta’lim bo‘yicha dekan o‘rinbosari', '', '', '17'),
  ('155', 'Yoshlar bilan ishlash bo‘yicha dekan o‘rinbosari', '', '', '17'),
  ('100', 'Ilmiy tadqiqot ishlari muhandisi', '', '', '17'),
  ('103', 'Ishlab chiqarish ta’limi ustasi', '', '', '17'),
  ('220', 'O''quv ustasi', '', '', '17'),
  ('37', 'Kabinet mudiri', '', '', '17'),
  ('113', 'Laboratoriya mudiri', '', '', '17'),
  ('61', 'Laborant', '', '', '17'),
  ('201', 'Muhandis (o’quv jihozlari bo’yicha I-toifali)', '', '', '17'),
  ('124', 'O‘quv ishlari bo‘yicha dispetcher', '', '', '17'),
  ('126', 'O‘quv ishlari bo‘yicha inspektor', '', '', '17'),
  ('127', 'O‘quv jihozlari bo‘yicha muhandis', '', '', '17'),
  ('139', 'Sirtqi (Maxsus sirtqi) ta’lim uchun o‘quv-metodik ishlar bo‘yicha uslubchi', '', '', '17'),
  ('158', 'Kechki (smenali) ta’lim uchun o‘quv-metodik ishlar bo‘yicha uslubchi', '', '', '17'),
  ('18', 'Uslubchi', '', '', '17'),
  ('229', 'Talabalar bilan ishlash bo''yicha koordinator', '', '', '17'),
  ('238', 'Ta’lim sifatini nazorat qilish bo''limi raisi', '', '', '17'),
  ('232', 'Surdotarjimon', '', '', '17'),
  ('239', 'Tarjimon', '', '', '17'),
  ('240', 'Menejer', '', '', '17'),
  ('53', 'Dispetcher', '', '', '17'),
  ('144', 'Tarbiyachi-pedagog', '', '', '17'),
  ('190', 'Tarbiyachi-uslubchi', '', '', '17'),
  ('133', 'Psixolog', '', '', '17'),
  ('34', 'Tyutor', '', '', '17'),
  ('191', 'Katta ilmiy xodim', '', '', '17'),
  ('192', 'Kichik ilmiy xodim', '', '', '17'),
  ('135', 'Sektor boshlig‘i', '', '', '18'),
  ('186', '1-toifali hisobchi', '', '', '18'),
  ('185', '2-toifali hisobchi', '', '', '18'),
  ('51', 'Bosh buxgalter', '', '', '18'),
  ('78', 'Bosh buxgalter o‘rinbosari', '', '', '18'),
  ('162', 'Bosh hisobchi', '', '', '18'),
  ('30', 'Buxgalter', '', '', '18'),
  ('93', 'G‘aznachi', '', '', '18'),
  ('218', 'Hisobchi', '', '', '18'),
  ('56', 'Iqtisodchi', '', '', '18'),
  ('199', 'Yetakchi buxgalter', '', '', '18'),
  ('200', 'Yetakchi iqtisodchi', '', '', '18'),
  ('223', 'Katta taʼminotchi', '', '', '18'),
  ('202', 'Ta’minot agenti (I toifali)', '', '', '18'),
  ('148', 'Xarid bo‘yicha bosh mutaxassis', '', '', '18'),
  ('105', 'Katta tovarshunos', '', '', '18'),
  ('42', 'Tarmoq administratori', '', '', '19'),
  ('40', 'Tizim administratori', '', '', '19'),
  ('235', 'Veb dasturchi', '', '', '19'),
  ('57', 'Veb-dizayner', '', '', '19'),
  ('236', 'Videomontaj bo''yicha texnik', '', '', '19'),
  ('197', 'Muhandis-sistema dasturchisi (I toifali)', '', '', '19'),
  ('198', 'Muhandis-sistema ma’muri', '', '', '19'),
  ('193', 'Muhandis-texnolog', '', '', '19'),
  ('110', 'Kompyuter zali mudiri', '', '', '19'),
  ('39', 'Muhandis dasturchi', '', '', '19'),
  ('44', 'Muhandis elektronchi', '', '', '19'),
  ('45', 'Texnik elektronchi', '', '', '19'),
  ('41', 'Kontent menejer', '', '', '19'),
  ('217', '2-toifali muhandis dasturchi', '', '', '19'),
  ('234', 'Dasturchi texnik', '', '', '19'),
  ('118', 'Mudir', '', '', '20'),
  ('119', 'Mudir o‘rinbosari', '', '', '20'),
  ('76', 'Bo‘lim mudiri', '', '', '20'),
  ('211', '1-toifali biblograf', '', '', '20'),
  ('213', '1-toifali elektron kutubxonachi', '', '', '20'),
  ('215', '1-toifali kutubxonachi', '', '', '20'),
  ('74', 'Axborot-kutubxona texnologiyalari bo‘yicha yetakchi mutaxassis', '', '', '20'),
  ('58', 'Bibliograf', '', '', '20'),
  ('80', 'Bosh kutubxonachi', '', '', '20'),
  ('59', 'Kutubxonachi', '', '', '20'),
  ('212', '2-toifali biblograf', '', '', '20'),
  ('214', '2-toifali kutubxonachi', '', '', '20'),
  ('196', 'Elektron kutubxonalar kutubxonachisi (II toifali)', '', '', '20'),
  ('89', 'Elektron kutubxonalar kutubxonachisi', '', '', '20'),
  ('216', 'Yetakchi kutubxonachi', '', '', '20'),
  ('194', 'Kutubxonachi (I toifali)', '', '', '20'),
  ('91', 'Fond saqlovchi', '', '', '20'),
  ('123', 'Muzey kuzatuvchisi', '', '', '20'),
  ('121', 'Muharrir', '', '', '20'),
  ('122', 'Musahhih', '', '', '20'),
  ('145', 'Texnik muharrir', '', '', '20'),
  ('173', 'Koordinator-muharrir', '', '', '20'),
  ('150', 'Xo‘jalik bo‘limi mudiri', '', '', '21'),
  ('129', 'Ombor mudiri', '', '', '21'),
  ('142', 'Talabalar turar joyi direktori', '', '', '21'),
  ('143', 'Talabalar turar joyi mudiri', '', '', '21'),
  ('206', 'Garaj boshlig‘i', '', '', '21'),
  ('146', 'Vivariy mudiri', '', '', '21'),
  ('132', 'Poligon mudiri', '', '', '21'),
  ('134', 'San’at saroyi mudiri', '', '', '21'),
  ('176', 'Madaniyat saroyi mudiri', '', '', '21'),
  ('140', 'Sport inshooti mudiri', '', '', '21'),
  ('141', 'Stansiya boshlig‘i', '', '', '21'),
  ('209', 'Xizmat boshlig‘i', '', '', '21'),
  ('75', 'Bino komendanti', '', '', '21'),
  ('64', 'Yotoqxona komendanti', '', '', '21'),
  ('210', 'Energiya manbalarini hisobga olish bo‘yicha muhandis (I toifali)', '', '', '21'),
  ('92', 'Fuqaro muhofazasi va favqulodda vaziyatlar bo‘yicha muhandis', '', '', '21'),
  ('85', 'Dispetcher-garaj mudiri', '', '', '21'),
  ('115', 'Mehnat muhofazasi bo‘yicha muhandis', '', '', '21'),
  ('163', 'Yong‘in xavfsizligi bo‘yicha instruktor', '', '', '21'),
  ('224', 'Bosh omborchi', '', '', '21'),
  ('130', 'Omborchi', '', '', '21'),
  ('67', 'Qorovul', '', '', '21'),
  ('70', 'Aloqa bo‘yicha texnik', '', '', '21'),
  ('72', 'Aloqachi (aloqa elektromontyori)', '', '', '21'),
  ('71', 'Aloqa muhandisi', '', '', '21'),
  ('77', 'Bog‘bon', '', '', '21'),
  ('82', 'Chilangar (santexnik)', '', '', '21'),
  ('225', 'Dazmolchi', '', '', '21'),
  ('86', 'Dispetcherlik xizmati operatori', '', '', '21'),
  ('87', 'Duradgor', '', '', '21'),
  ('66', 'Farrosh', '', '', '21'),
  ('207', 'Garaj mexanigi (II toifali)', '', '', '21'),
  ('94', 'Garderobchi', '', '', '21'),
  ('95', 'Gazpayvandlovchi', '', '', '21'),
  ('88', 'Elektromontyor', '', '', '21'),
  ('203', 'Elektr uskunalariga xizmat ko‘rsatish va ta’mirlash bo‘yicha elektromontyor', '', '', '21'),
  ('97', 'Haydovchi', '', '', '21'),
  ('108', 'Kimyoviy usulda tozalovchi', '', '', '21'),
  ('178', 'Kir yuvuvchi', '', '', '21'),
  ('109', 'Ko‘cha supuruvchi', '', '', '21'),
  ('69', 'Konditsiyalash va shamollatish sistemasini ta’mirlash va unga xizmat ko‘rsatish bo‘yicha chilangar', '', '', '21'),
  ('116', 'Mexanik', '', '', '21'),
  ('222', 'Qog''oz kesuvchi', '', '', '21'),
  ('219', 'Qozonxona o‘t yoquvchisi', '', '', '21'),
  ('128', 'O‘t yoquvchi', '', '', '21'),
  ('228', 'Sport menejeri', '', '', '21'),
  ('114', 'Liftchi', '', '', '21'),
  ('226', 'Tikuv ustasi', '', '', '21'),
  ('161', 'Tuzatuvchi', '', '', '21'),
  ('149', 'Xo‘jalik bekasi', '', '', '21'),
  ('154', 'Yordamchi ishchi', '', '', '21'),
  ('102', 'Ishchi', '', '', '21'),
  ('157', 'Yuklovchi', '', '', '21'),
  ('136', 'Sektor mudiri', '', '', '22'),
  ('60', 'Arxivarius', '', '', '22'),
  ('73', 'Arxiv mudiri', '', '', '22'),
  ('83', 'Devonxona mudiri', '', '', '22'),
  ('62', 'Kuryer', '', '', '22'),
  ('230', 'Kadrlar bilan ishlash bo''yicha mutaxassis', '', '', '22'),
  ('188', 'Kadrlar bo’yicha inspektor (I toifali)', '', '', '22'),
  ('187', 'Kadrlar bo’yicha yetakchi muhandis', '', '', '22'),
  ('151', 'Xodimlar bo‘yicha muhandis', '', '', '22'),
  ('159', '2-toifali Xodimlar bo‘yicha muhandis', '', '', '22'),
  ('27', 'Inspektor', '', '', '22'),
  ('160', 'Nozir', '', '', '22'),
  ('169', 'Ovoz rejissyori', '', '', '23'),
  ('166', 'Radiostudiya prodyuseri', '', '', '23'),
  ('168', 'Sahnalashtiruvchi', '', '', '23'),
  ('165', 'Telestudiya prodyuseri', '', '', '23'),
  ('152', 'Yetakchi konsertmeyster', '', '', '23'),
  ('111', 'Konsertmeyster', '', '', '23'),
  ('172', 'Montaj ustasi', '', '', '23'),
  ('171', 'Chiroq ustasi', '', '', '23'),
  ('167', 'Efir rejissyori', '', '', '23'),
  ('174', 'Grim ustasi', '', '', '23'),
  ('170', 'Operator', '', '', '23'),
  ('175', 'Operator assistenti', '', '', '23'),
  ('137', 'Shifokor (vrach)', '', '', '23'),
  ('204', 'Tibbiyot hamshirasi (I toifali)', '', '', '23'),
  ('205', 'Tibbiyot hamshirasi (toifasiz)', '', '', '23'),
  ('96', 'Hamshira', '', '', '23'),
  ('227', 'Agronom', '', '', '23'),
  ('231', 'Biolog seleksiyachi', '', '', '23')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, type_code = EXCLUDED.type_code;
