-- =====================================================
-- S017: 2026 supplementary specialities (h_speciality + h_speciality_year)
-- =====================================================
-- Source: docs/mutaxasisliklar/Бакалавр-кушимча-2026.xlsx + Магистр-кушимча-2026.xlsx
--         (65 NEW L3 leaves, year 2026). Generated by etl_speciality_kushimcha_2026.py.
-- DO NOT hand-edit — re-run the ETL.
-- MANUAL ADDITION (2026-08-08, user-confirmed): NEW L3 leaf d32852a3 (70320401 'Axborot-kutubxona
--   faoliyati', MASTER, parent 66abfbe8) bound to 2026 -- a reordered name of the S014 sibling
--   'Kutubxona axborot faoliyati'. name_oz is a transliteration; name_ru/en NULL (enrich in FE).
--   Not from the ETL xlsx -- re-add if the ETL re-runs.
-- MANUAL CORRECTION (2026-08-08, user-confirmed): row 3d79d732 (70410112) renamed --
--   name_uz 'Tsirkulyar iqtisodiyot' -> 'Sirkulyar iqtisodiyot' AND name_oz
--   'Циркуляр иқтисодиёт' -> 'Сиркуляр иқтисодиёт'. Re-apply if the ETL re-runs.
-- MANUAL ADDITION (2026-08-08, user-confirmed): NEW L3 leaf f5fb6051 (70910102 'Yuz-jagʻ jarrohligi',
--   MASTER, parent 1f1187c0) bound to 2026 -- native-Uzbek rename of the S014 sibling 'Yuz-jagʻ
--   xirurgiyasi' (which keeps 2021/2023/2024; its 2026 was dropped from S015). name_oz is a
--   transliteration; name_en mirrors the sibling ('Maxillofacial surgery'). Re-add if the ETL re-runs.
-- MANUAL ADDITION (2026-08-08, user-confirmed): NEW L3 leaf 0fe57a24 (70910212 'Jarrohlik', MASTER,
--   parent 1f1187c0 -- SAME parent as its sibling 'Xirurgiya', which is correct) bound to 2026. Native-
--   Uzbek rename of 'Xirurgiya' (which keeps 2024; its 2026 was dropped from S015). name_oz is a
--   transliteration; name_en mirrors the sibling ('Surgery'). Re-add if the ETL re-runs.
-- MANUAL ADDITION (2026-08-08, user-confirmed): NEW L3 leaf 7fdf94cf (70910214 'Neyrojarrohlik',
--   MASTER, parent 1f1187c0 -- same parent as sibling 'Neyroxirurgiya') bound to 2026. Native-Uzbek
--   rename of 'Neyroxirurgiya' (which keeps 2021/2023/2024; its 2026 was dropped from S015). name_oz
--   is a transliteration; name_en mirrors the sibling ('Neurosurgery'). Re-add if the ETL re-runs.
-- MANUAL ADDITION (2026-08-08, user-confirmed): NEW L3 leaf 7670a4eb (70910302 'Bolalar jarrohligi',
--   MASTER, parent 1f1187c0 -- same parent as sibling 'Bolalar xirurgiyasi') bound to 2026. Native-
--   Uzbek rename of 'Bolalar xirurgiyasi' (which keeps 2021/2023/2024; its 2026 was dropped from S015).
--   name_oz transliteration; name_en 'Pediatric surgery' (sibling's stray trailing '.' dropped). Re-add if ETL re-runs.
-- MANUAL ADDITION (2026-08-08, user-confirmed): NEW L3 leaf bc02fd15 (71031301 'Jamoat xavfsizligini
--   huquqiy taʼminlash' -- tutuq belgisi ʼ = U+02BC, like existing 'taʼminlash' rows; MASTER, parent
--   4a12a620 = same as sibling 'Jamoat xavfsizligi') bound to 2026. Sibling keeps 2021/2023/2024;
--   its 2026 was dropped from S015. name_oz Cyrillic; name_en mirrors sibling. Re-add if the ETL re-runs.
-- IDENTITY RULE (ministry, user-confirmed): a leaf is placed by (education_type, code, name),
--   NOT by its free-text note. A leaf whose (edu, code, name) does NOT already exist is inserted
--   as a NEW uuid5 row + 2026 — this covers 'code re-assigned' (шифри ўзгарган: same name, new
--   code) and 'a new name under an existing code' alike. A leaf whose exact (edu, code, name)
--   already exists is a NO-OP (it already carries 2026 via S014/S015) or a LINK (only the 2026
--   year is added to that existing id, below). NOTHING is retired: same-code/different-name and
--   same-name/different-code both stay distinct rows (they differ in the identity key).
-- ADDITIVE over S014/S015 — those are NOT touched. One code may be shared by several rows with
--   different names (e.g. MASTER 70530402 = Gidrogeologiya AND Suv resurslarini boshqarish); the
--   (education_type, code, name_search) UNIQUE permits that and each row's 2026 link is its own.
-- id = uuid5(edu|code) — stable across later name corrections so a re-run never forks.
-- name_oz = original Cyrillic (authoritative ministry source); name_uz = machine transliteration,
--   name_ru/name_en may be enriched later in the FE. review_status = APPROVED — these are official
--   2026 ministry specialities (Excel source), so like S014 they are born APPROVED and therefore
--   distributable to the 224 OTMs. name_search is a GENERATED column (V018) — not inserted here;
--   edu_form was dropped. ON CONFLICT (id) DO NOTHING never overwrites FE edits. Escalations
--   (NO-OP / LINK) are logged to the ETL REVIEW CSV.
-- =====================================================


INSERT INTO h_speciality (id,code,name_uz,name_oz,name_ru,name_en,education_type,review_status,parent_id,hierarchy_level,active,is_checked,version) VALUES
  ('93617c85-1605-5d54-aa1e-73b1c4b67106','60411500','Davlat auditi','Давлат аудити',NULL,NULL,'11','APPROVED','d6ec1be6-c242-4eb6-9ef7-092250331b99',3,true,false,1),
  ('defdd731-e9fe-51e1-84ea-77c198e2577c','60411600','Islomiy moliya','Исломий молия',NULL,NULL,'11','APPROVED','d6ec1be6-c242-4eb6-9ef7-092250331b99',3,true,false,1),
  ('0ef5c1a2-faac-58bb-80f4-f6d2979b9e4f','60411700','Islom iqtisodiyoti va moliyasi','Ислом иқтисодиёти ва молияси',NULL,NULL,'11','APPROVED','d6ec1be6-c242-4eb6-9ef7-092250331b99',3,true,false,1),
  ('68cefdae-c501-5915-b405-b6fc1447df35','60411800','Yashil iqtisodiyot','Яшил иқтисодиёт',NULL,NULL,'11','APPROVED','d6ec1be6-c242-4eb6-9ef7-092250331b99',3,true,false,1),
  ('efeb19b4-6a0a-522b-92ca-4e3e25c75e46','60421400','Xalqaro huquq va qiyosiy huquqshunoslik','Халқаро ҳуқуқ ва қиёсий ҳуқуқшунослик',NULL,NULL,'11','APPROVED','beb8ab45-3536-4e89-92d1-52c933bc8a7d',3,true,false,1),
  ('91beda8a-1e0d-4448-e075-bb3d862e61c7','60421400','Xalqaro aloqalar va huquq',NULL,NULL,'BA (Hons) in International Relations and Law','11','APPROVED','efeb19b4-6a0a-522b-92ca-4e3e25c75e46',4,true,false,2),
  ('4efe2fec-36b2-5f1a-8ad5-0d63ad88d820','60421500','Raqamli huquq','Рақамли ҳуқуқ',NULL,NULL,'11','APPROVED','beb8ab45-3536-4e89-92d1-52c933bc8a7d',3,true,false,1),
  ('4c19ed4b-b43a-5ebd-a653-ae9b25fcaeda','60421600','Kiberhuquq','Киберҳуқуқ',NULL,NULL,'11','APPROVED','beb8ab45-3536-4e89-92d1-52c933bc8a7d',3,true,false,1),
  ('97bc62a7-bc54-5573-90f5-c28f86c25f7d','60520300','Atrof-muhit va barqaror boshqaruv','Атроф-муҳит ва барқарор бошқарув',NULL,NULL,'11','APPROVED','675beeba-cda1-488e-96ba-f5b210e6e399',3,true,false,1),
  ('2086eacc-e81c-5c9c-9a8c-53a1ddefac6d','60520400','Atrof-muhit muhandisligi va qayta tiklanuvchi energiya','Атроф-муҳит муҳандислиги ва қайта тикланувчи энергия',NULL,NULL,'11','APPROVED','675beeba-cda1-488e-96ba-f5b210e6e399',3,true,false,1),
  ('c22912e0-b7c9-5d1f-8819-37d26c7e95c6','60520500','Iqlim oʻzgarishi va barqaror rivojlanish','Иқлим ўзгариши ва барқарор ривожланиш',NULL,NULL,'11','APPROVED','675beeba-cda1-488e-96ba-f5b210e6e399',3,true,false,1),
  ('412dbf15-10fd-5154-ba2b-be2c8c26a87e','60520600','Gidrometeorologiya va suv resurslarini boshqarish','Гидрометеорология ва сув ресурсларини бошқариш',NULL,NULL,'11','APPROVED','675beeba-cda1-488e-96ba-f5b210e6e399',3,true,false,1),
  ('2b11e3d1-f776-54d4-881e-cf1f14d0cf40','60611300','Sunʼiy intellekt va kiberxavfsizlik','Сунъий интеллект ва киберхавфсизлик',NULL,NULL,'11','APPROVED','f51dd7d0-bb53-4734-9eaf-602930c7a950',3,true,false,1),
  ('d2253198-1ec3-5cee-8647-c7ec293aedc6','60712400','Mobil robotlar va uchuvchisiz uchish apparatlari','Мобил роботлар ва учувчисиз учиш аппаратлари',NULL,NULL,'11','APPROVED','9a888a11-8dcf-4ce3-8eee-d3fe0a16a63f',3,true,false,1),
  ('75aaabb1-567d-58bd-824c-43786e156602','60731100','Qurilish materiallari, buyumlari va konstruktsiyalarini ishlab chiqarish','Қурилиш материаллари, буюмлари ва конструкцияларини ишлаб чиқариш',NULL,NULL,'11','APPROVED','424d2c91-1144-41da-bdbf-e183f677e9bd',3,true,false,1),
  ('7cb2bd9b-1e06-5064-bc45-24fae0286c01','60811800','Barqaror qishloq xoʻjaligi va oziq-ovqat tizimlari','Барқарор қишлоқ хўжалиги ва озиқ-овқат тизимлари',NULL,NULL,'11','APPROVED','aaedaec0-7b25-4700-807c-dfb3ef21f6e8',3,true,false,1),
  ('632252cd-9bf3-5486-b94b-21e8a0f9ff2a','60811900','Choʻllanishga qarshi kurashish va choʻl iqtisodiyoti','Чўлланишга қарши курашиш ва чўл иқтисодиёти',NULL,NULL,'11','APPROVED','aaedaec0-7b25-4700-807c-dfb3ef21f6e8',3,true,false,1),
  ('2430d4df-7d95-5bf6-ac29-53ddfdc99814','60911000','Parameditsina','Парамедицина',NULL,NULL,'11','APPROVED','960be177-4e20-4a3c-b381-a1d816370e3f',3,true,false,1),
  ('719856f5-4294-5601-946c-f134f8880dbc','61030200','Xizmat faoliyatini tarbiyaviy-psixologik taʼminlash','Хизмат фаолиятини тарбиявий-психологик таъминлаш',NULL,NULL,'11','APPROVED','deb2303d-10db-42d3-adca-3a6d5dcbefd9',3,true,false,1),
  ('6598be69-e94f-5205-980e-7b7437524bed','61032200','Yoʻl patrul xizmatining qoʻmondonlik-taktik faoliyati','Йўл патруль хизматининг қўмондонлик-тактик фаолияти',NULL,NULL,'11','APPROVED','deb2303d-10db-42d3-adca-3a6d5dcbefd9',3,true,false,1),
  ('18a3b952-0305-54b3-8e5d-2fb7302e3ba3','61032300','Patrul-post xizmatining qoʻmondonlik-taktik faoliyati','Патрул-пост хизматининг қўмондонлик-тактик фаолияти',NULL,NULL,'11','APPROVED','deb2303d-10db-42d3-adca-3a6d5dcbefd9',3,true,false,1),
  ('cd93373b-ab48-5f35-9fc0-fd28be31bc97','61032400','Pasport tizimini huquqiy taʼminlash','Паспорт тизимини ҳуқуқий таъминлаш',NULL,NULL,'11','APPROVED','deb2303d-10db-42d3-adca-3a6d5dcbefd9',3,true,false,1),
  ('61b24850-8aa7-5bfc-87a2-6ab89e1ecb26','61032500','Iqtisodiy xavfsizlik','Иқтисодий хавфсизлик',NULL,NULL,'11','APPROVED','deb2303d-10db-42d3-adca-3a6d5dcbefd9',3,true,false,1),
  ('45b8d385-636b-5d0f-b190-e927ceb73c7c','61040400','Temir yoʻlda tashish muhandisligi','Темир йўлда ташиш муҳандислиги',NULL,NULL,'11','APPROVED','88e8014f-c1c5-44e1-b79e-215a538193b7',3,true,false,1),
  ('0cde63c9-e32b-5b03-b5a5-248211d24061','70110302','Gospital pedagogika','Госпиталь педагогика',NULL,NULL,'12','APPROVED','548d8dea-d0ea-44ab-afcd-a205bfe7a41a',3,true,false,1),
  ('abebaf32-c798-5bee-8611-f302c8c20c3e','70220104','Diniy-maʼrifiy soha menejmenti','Диний-маърифий соҳа менежменти',NULL,NULL,'12','APPROVED','07d1ccee-049d-4af7-88b0-0d67f0ef98dc',3,true,false,1),
  ('eb1d1179-9526-54c7-8c13-f21571c8cd4b','70310206','Xalqaro energetik siyosat','Халқаро энергетик сиёсат',NULL,NULL,'12','APPROVED','ed932734-6429-451f-be51-f126c0bbb08a',3,true,false,1),
  ('31d76d74-a415-5eb5-b55a-9b805884284b','70310207','Xalqaro xavfsizlik','Халқаро хавфсизлик',NULL,NULL,'12','APPROVED','ed932734-6429-451f-be51-f126c0bbb08a',3,true,false,1),
  ('43bd3b8e-5106-548a-b967-f41415401f3e','70310208','Xalqaro suv diplomatiyasi','Халқаро сув дипломатияси',NULL,NULL,'12','APPROVED','ed932734-6429-451f-be51-f126c0bbb08a',3,true,false,1),
  ('3d79d732-af32-5282-a0d9-96859ea84619','70410112','Sirkulyar iqtisodiyot','Сиркуляр иқтисодиёт',NULL,NULL,'12','APPROVED','72e2440a-4428-4f56-aa2c-97defc746a67',3,true,false,1),
  ('75799739-0db6-5490-beb3-de39a7d2bf8a','70410512','Davlat moliyasini boshqarish','Давлат молиясини бошқариш',NULL,NULL,'12','APPROVED','72e2440a-4428-4f56-aa2c-97defc746a67',3,true,false,1),
  ('b13b5bfe-5fc2-5e6d-a389-ff58acd98a05','70410513','Barqaror moliya','Барқарор молия',NULL,NULL,'12','APPROVED','72e2440a-4428-4f56-aa2c-97defc746a67',3,true,false,1),
  ('2ac3434a-9e87-504b-8dcd-02e64c3f4ca5','70410805','Intellektual mulk obyektlarini boshqarish','Интеллектуал мулк объектларини бошқариш',NULL,NULL,'12','APPROVED','72e2440a-4428-4f56-aa2c-97defc746a67',3,true,false,1),
  ('52493ba8-b730-5fad-bde4-0dab605600e2','70410806','Yashil loyihalar boshqaruvi','Яшил лойиҳалар бошқаруви',NULL,NULL,'12','APPROVED','72e2440a-4428-4f56-aa2c-97defc746a67',3,true,false,1),
  ('7a116290-3915-525b-8b84-030423d8d1fc','70411103','Rivojlanish iqtisodiyoti','Ривожланиш иқтисодиёти',NULL,NULL,'12','APPROVED','72e2440a-4428-4f56-aa2c-97defc746a67',3,true,false,1),
  ('e95e4e86-cfd5-567a-8366-fd916d0251d0','70411104','Iqtisodiyotda katta maʼlumotlarni tahlil qilish va modellashtirish','Иқтисодиётда катта маълумотларни таҳлил қилиш ва моделлаштириш',NULL,NULL,'12','APPROVED','72e2440a-4428-4f56-aa2c-97defc746a67',3,true,false,1),
  ('8cd6ce4c-9c66-5fa6-a63e-4db8922b6e9a','70411501','Davlat auditi va moliyaviy nazorat','Давлат аудити ва молиявий назорат',NULL,NULL,'12','APPROVED','72e2440a-4428-4f56-aa2c-97defc746a67',3,true,false,1),
  ('245ecf1f-b557-5f4b-8027-39b0fc59a285','70411601','Islomiy moliya','Исломий молия',NULL,NULL,'12','APPROVED','72e2440a-4428-4f56-aa2c-97defc746a67',3,true,false,1),
  ('145b754d-5c4f-5010-bdb6-5704a839bac7','70411701','Islom iqtisodiyoti va moliyasi','Ислом иқтисодиёти ва молияси',NULL,NULL,'12','APPROVED','72e2440a-4428-4f56-aa2c-97defc746a67',3,true,false,1),
  ('1247bebf-e404-5db7-b907-1f14a4374833','70420131','Huquqiy siyosat, davlat boshqaruvida strategik rejalashtirish','Ҳуқуқий сиёсат, давлат бошқарувида стратегик режалаштириш',NULL,NULL,'12','APPROVED','d60d20bb-9ab8-447c-a300-a9c541cf5a4c',3,true,false,1),
  ('7fe03ca4-e170-5ec1-81c4-f63af8d1dec3','70420132','Korporativ huquq va boshqaruv','Корпоратив ҳуқуқ ва бошқарув',NULL,NULL,'12','APPROVED','d60d20bb-9ab8-447c-a300-a9c541cf5a4c',3,true,false,1),
  ('b7b682b2-9a9e-5310-a846-622ecfc67677','70420133','Huquqiy boshqaruv (Master of Legal administration - MLA)','Ҳуқуқий бошқарув (Master of Legal administration - MLA)',NULL,NULL,'12','APPROVED','d60d20bb-9ab8-447c-a300-a9c541cf5a4c',3,true,false,1),
  ('fecae4d6-1d44-5bfd-9cc3-45d6d81a5f06','70420134','Ekologiya huquqi','Экология ҳуқуқи',NULL,NULL,'12','APPROVED','d60d20bb-9ab8-447c-a300-a9c541cf5a4c',3,true,false,1),
  ('aeb939ad-e1e3-5842-8f80-57d9c232e1c3','70420135','Xalqaro savdo huquqi','Халқаро савдо ҳуқуқи',NULL,NULL,'12','APPROVED','d60d20bb-9ab8-447c-a300-a9c541cf5a4c',3,true,false,1),
  ('23d40b27-4f06-5973-a49b-b133a807e9d2','70420205','Davlat siyosati','Давлат сиёсати',NULL,NULL,'12','APPROVED','d60d20bb-9ab8-447c-a300-a9c541cf5a4c',3,true,false,1),
  ('9c437a88-cdfd-53d3-941e-7806c80fa511','70420206','Mahalla boshqaruvi','Маҳалла бошқаруви',NULL,NULL,'12','APPROVED','d60d20bb-9ab8-447c-a300-a9c541cf5a4c',3,true,false,1),
  ('94af5511-9ea3-5f6c-b91f-434d92aaadd8','70420207','Hududiy rejalashtirish va rivojlantirish','Ҳудудий режалаштириш ва ривожлантириш',NULL,NULL,'12','APPROVED','d60d20bb-9ab8-447c-a300-a9c541cf5a4c',3,true,false,1),
  ('02aaab8c-d703-5c61-9b64-bc9f4399cebf','70420208','Liderlik va barqaror rivojlanish','Лидерлик ва барқарор ривожланиш',NULL,NULL,'12','APPROVED','d60d20bb-9ab8-447c-a300-a9c541cf5a4c',3,true,false,1),
  ('52d82197-534a-55fe-a30a-7259a6a2bb77','70420209','Ijtimoiy loyihalarni boshqarish va muvofiqlashtirish','Ижтимоий лойиҳаларни бошқариш ва мувофиқлаштириш',NULL,NULL,'12','APPROVED','d60d20bb-9ab8-447c-a300-a9c541cf5a4c',3,true,false,1),
  ('089cde81-a6f7-52b0-8d4c-2bdd92dd8dba','70420210','Barqaror rivojlanish','Барқарор ривожланиш',NULL,NULL,'12','APPROVED','d60d20bb-9ab8-447c-a300-a9c541cf5a4c',3,true,false,1),
  ('68c92d57-9926-550f-8913-3772b32a9f4e','70520206','Ekologiya va sunʼiy intellekt texnologiyalari','Экология ва сунъий интеллект технологиялари',NULL,NULL,'12','APPROVED','622c3c49-5b16-45ed-a6ef-6a709c21ce17',3,true,false,1),
  ('4d96f93d-a0b1-5723-81d0-0c6ee437e7c6','70520301','Atrof-muhit sohasida ommaviy kommunikatsiya','Атроф-муҳит соҳасида оммавий коммуникация',NULL,NULL,'12','APPROVED','622c3c49-5b16-45ed-a6ef-6a709c21ce17',3,true,false,1),
  ('77f83c17-253b-519d-a935-bbfbf51f8b0a','70530311','Gidrogeologiya','Гидрогеология',NULL,NULL,'12','APPROVED','b0268129-6513-463b-9045-55b5869a1867',3,true,false,1),
  ('a3f9c4a8-1493-523c-ab46-4bb2e5fe6022','70530402','Suv resurslarini boshqarish','Сув ресурсларини бошқариш',NULL,NULL,'12','APPROVED','b0268129-6513-463b-9045-55b5869a1867',3,true,false,1),
  ('3e8a709f-3223-5b54-be27-24998ba6e117','70530403','Gidravlika','Гидравлика',NULL,NULL,'12','APPROVED','b0268129-6513-463b-9045-55b5869a1867',3,true,false,1),
  ('8bbcd2a1-78b5-50fc-aa92-a5740ccc47cc','70530511','Nazariy fizika','Назарий физика',NULL,NULL,'12','APPROVED','b0268129-6513-463b-9045-55b5869a1867',3,true,false,1),
  ('3152c76a-2916-5427-a176-78e743fff620','70530512','Muhandislik fizikasi','Муҳандислик физикаси',NULL,NULL,'12','APPROVED','b0268129-6513-463b-9045-55b5869a1867',3,true,false,1),
  ('41e430cd-36a5-5f30-a4e5-dca716781516','70611202','Kiberxavfsizlik injiniringi','Киберхавфсизлик инжиниринги',NULL,NULL,'12','APPROVED','b3465b98-11f1-480a-a155-d7178f98519e',3,true,false,1),
  ('802c9917-b57f-5497-897a-3f0bbf7309ec','70710414','Barqaror energiya almashinuvi','Барқарор энергия алмашинуви',NULL,NULL,'12','APPROVED','9c30a392-a17c-452c-8080-97c0847993a3',3,true,false,1),
  ('b8563297-03fd-5171-a45d-7ee5bce55544','70712401','Mobil robotlar va uchuvchisiz uchish apparatlari','Мобил роботлар ва учувчисиз учиш аппаратлари',NULL,NULL,'12','APPROVED','9c30a392-a17c-452c-8080-97c0847993a3',3,true,false,1),
  ('4ff70462-0f5a-5efd-8162-cf774bb18b4e','70730309','Favqulodda holat talablari asosida bino va inshootlarni loyihalash va qurish','Фавқулодда ҳолат талаблари асосида бино ва иншоотларни лойиҳалаш ва қуриш',NULL,NULL,'12','APPROVED','ed9be9e2-529a-42c2-8eee-51322d71d658',3,true,false,1),
  ('cca5bdab-944f-5be5-af55-b42dd7cc0d22','70730901','Urbanistika (geourbanistika), shahar va aglomeratsiyalarni strategik rejalashtirish','Урбанистика (геоурбанистика), шаҳар ва агломерацияларни стратегик режалаштириш',NULL,NULL,'12','APPROVED','ed9be9e2-529a-42c2-8eee-51322d71d658',3,true,false,1),
  ('fee765fb-1ed8-5ccc-b704-572d77e3174c','70730902','Barqaror shaharsozlik','Барқарор шаҳарсозлик',NULL,NULL,'12','APPROVED','ed9be9e2-529a-42c2-8eee-51322d71d658',3,true,false,1),
  ('4ff4720d-28fe-515c-a030-a1436f6d2a29','70820103','Iqlimga chidamli oʻrmon xoʻjaligi','Иқлимга чидамли ўрмон хўжалиги',NULL,NULL,'12','APPROVED','6ce56215-9340-4ee1-a94f-6d2f632a6420',3,true,false,1),
  ('74572494-e045-56c3-bb61-a45220333380','70910235','Allergologiya va klinik immunologiya','Аллергология ва клиник иммунология',NULL,NULL,'12','APPROVED','1f1187c0-3bff-4fa0-8be1-4acd6f63a17e',3,true,false,1),
  ('a5541f57-2351-54de-88ee-d29022b3b714','71040401','Temir yoʻlda tashish muhandisligi','Темир йўлда ташиш муҳандислиги',NULL,NULL,'12','APPROVED','161dc667-1d2f-4e61-a2f1-4a3ebaea5c91',3,true,false,1),
  ('d32852a3-b2b6-4064-b9e8-c869b382be05','70320401','Axborot-kutubxona faoliyati','Ахборот-кутубхона фаолияти',NULL,NULL,'12','APPROVED','66abfbe8-916a-424f-952e-ef9ac033dc40',3,true,false,1),
  ('f5fb6051-80a7-4a33-9c78-b0abd5b32bde','70910102','Yuz-jagʻ jarrohligi','Юз-жағ жарроҳлиги',NULL,'Maxillofacial surgery','12','APPROVED','1f1187c0-3bff-4fa0-8be1-4acd6f63a17e',3,true,false,1),
  ('0fe57a24-808d-4f9d-acd3-3e09422e4420','70910212','Jarrohlik','Жарроҳлик',NULL,'Surgery','12','APPROVED','1f1187c0-3bff-4fa0-8be1-4acd6f63a17e',3,true,false,1),
  ('7fdf94cf-da05-49ad-b9b9-5cccd57a7e97','70910214','Neyrojarrohlik','Нейрожарроҳлик',NULL,'Neurosurgery','12','APPROVED','1f1187c0-3bff-4fa0-8be1-4acd6f63a17e',3,true,false,1),
  ('7670a4eb-eaad-4cb3-8f2d-fded64423bf4','70910302','Bolalar jarrohligi','Болалар жарроҳлиги',NULL,'Pediatric surgery','12','APPROVED','1f1187c0-3bff-4fa0-8be1-4acd6f63a17e',3,true,false,1),
  ('bc02fd15-8919-462b-b04b-60c0a63ad3bd','71031301','Jamoat xavfsizligini huquqiy taʼminlash','Жамоат хавфсизлигини ҳуқуқий таъминлаш',NULL,'Legal assurance of public safety','12','APPROVED','4a12a620-a297-4512-8894-e6c20516328b',3,true,false,1)
ON CONFLICT (id) DO NOTHING;


-- Years (2026; FK -> h_education_year, seeded in V018).

INSERT INTO h_speciality_year (speciality_id, year) VALUES
  ('93617c85-1605-5d54-aa1e-73b1c4b67106',2026),
  ('defdd731-e9fe-51e1-84ea-77c198e2577c',2026),
  ('0ef5c1a2-faac-58bb-80f4-f6d2979b9e4f',2026),
  ('68cefdae-c501-5915-b405-b6fc1447df35',2026),
  ('efeb19b4-6a0a-522b-92ca-4e3e25c75e46',2026),
  ('91beda8a-1e0d-4448-e075-bb3d862e61c7',2026),
  ('4efe2fec-36b2-5f1a-8ad5-0d63ad88d820',2026),
  ('4c19ed4b-b43a-5ebd-a653-ae9b25fcaeda',2026),
  ('97bc62a7-bc54-5573-90f5-c28f86c25f7d',2026),
  ('2086eacc-e81c-5c9c-9a8c-53a1ddefac6d',2026),
  ('c22912e0-b7c9-5d1f-8819-37d26c7e95c6',2026),
  ('412dbf15-10fd-5154-ba2b-be2c8c26a87e',2026),
  ('2b11e3d1-f776-54d4-881e-cf1f14d0cf40',2026),
  ('d2253198-1ec3-5cee-8647-c7ec293aedc6',2026),
  ('75aaabb1-567d-58bd-824c-43786e156602',2026),
  ('7cb2bd9b-1e06-5064-bc45-24fae0286c01',2026),
  ('632252cd-9bf3-5486-b94b-21e8a0f9ff2a',2026),
  ('2430d4df-7d95-5bf6-ac29-53ddfdc99814',2026),
  ('719856f5-4294-5601-946c-f134f8880dbc',2026),
  ('6598be69-e94f-5205-980e-7b7437524bed',2026),
  ('18a3b952-0305-54b3-8e5d-2fb7302e3ba3',2026),
  ('cd93373b-ab48-5f35-9fc0-fd28be31bc97',2026),
  ('61b24850-8aa7-5bfc-87a2-6ab89e1ecb26',2026),
  ('45b8d385-636b-5d0f-b190-e927ceb73c7c',2026),
  ('0cde63c9-e32b-5b03-b5a5-248211d24061',2026),
  ('abebaf32-c798-5bee-8611-f302c8c20c3e',2026),
  ('eb1d1179-9526-54c7-8c13-f21571c8cd4b',2026),
  ('31d76d74-a415-5eb5-b55a-9b805884284b',2026),
  ('43bd3b8e-5106-548a-b967-f41415401f3e',2026),
  ('3d79d732-af32-5282-a0d9-96859ea84619',2026),
  ('75799739-0db6-5490-beb3-de39a7d2bf8a',2026),
  ('b13b5bfe-5fc2-5e6d-a389-ff58acd98a05',2026),
  ('2ac3434a-9e87-504b-8dcd-02e64c3f4ca5',2026),
  ('52493ba8-b730-5fad-bde4-0dab605600e2',2026),
  ('7a116290-3915-525b-8b84-030423d8d1fc',2026),
  ('e95e4e86-cfd5-567a-8366-fd916d0251d0',2026),
  ('8cd6ce4c-9c66-5fa6-a63e-4db8922b6e9a',2026),
  ('245ecf1f-b557-5f4b-8027-39b0fc59a285',2026),
  ('145b754d-5c4f-5010-bdb6-5704a839bac7',2026),
  ('1247bebf-e404-5db7-b907-1f14a4374833',2026),
  ('7fe03ca4-e170-5ec1-81c4-f63af8d1dec3',2026),
  ('b7b682b2-9a9e-5310-a846-622ecfc67677',2026),
  ('fecae4d6-1d44-5bfd-9cc3-45d6d81a5f06',2026),
  ('aeb939ad-e1e3-5842-8f80-57d9c232e1c3',2026),
  ('23d40b27-4f06-5973-a49b-b133a807e9d2',2026),
  ('9c437a88-cdfd-53d3-941e-7806c80fa511',2026),
  ('94af5511-9ea3-5f6c-b91f-434d92aaadd8',2026),
  ('02aaab8c-d703-5c61-9b64-bc9f4399cebf',2026),
  ('52d82197-534a-55fe-a30a-7259a6a2bb77',2026),
  ('089cde81-a6f7-52b0-8d4c-2bdd92dd8dba',2026),
  ('68c92d57-9926-550f-8913-3772b32a9f4e',2026),
  ('4d96f93d-a0b1-5723-81d0-0c6ee437e7c6',2026),
  ('77f83c17-253b-519d-a935-bbfbf51f8b0a',2026),
  ('a3f9c4a8-1493-523c-ab46-4bb2e5fe6022',2026),
  ('3e8a709f-3223-5b54-be27-24998ba6e117',2026),
  ('8bbcd2a1-78b5-50fc-aa92-a5740ccc47cc',2026),
  ('3152c76a-2916-5427-a176-78e743fff620',2026),
  ('41e430cd-36a5-5f30-a4e5-dca716781516',2026),
  ('802c9917-b57f-5497-897a-3f0bbf7309ec',2026),
  ('b8563297-03fd-5171-a45d-7ee5bce55544',2026),
  ('4ff70462-0f5a-5efd-8162-cf774bb18b4e',2026),
  ('cca5bdab-944f-5be5-af55-b42dd7cc0d22',2026),
  ('fee765fb-1ed8-5ccc-b704-572d77e3174c',2026),
  ('4ff4720d-28fe-515c-a030-a1436f6d2a29',2026),
  ('74572494-e045-56c3-bb61-a45220333380',2026),
  ('a5541f57-2351-54de-88ee-d29022b3b714',2026),
  ('d32852a3-b2b6-4064-b9e8-c869b382be05',2026),
  ('f5fb6051-80a7-4a33-9c78-b0abd5b32bde',2026),
  ('0fe57a24-808d-4f9d-acd3-3e09422e4420',2026),
  ('7fdf94cf-da05-49ad-b9b9-5cccd57a7e97',2026),
  ('7670a4eb-eaad-4cb3-8f2d-fded64423bf4',2026),
  ('bc02fd15-8919-462b-b04b-60c0a63ad3bd',2026)
ON CONFLICT (speciality_id, year) DO NOTHING;

-- ---------------------------------------------------------------------------
-- CURATION (manual): re-parent 60911300 Parameditsina (Bakalavr, id c470f50d,
-- defined in S014) UNDER the new 2026 L3 60911000 Parameditsina (id 2430d4df,
-- inserted above). Done as an UPDATE here — a forward parent_id in S014 pointing
-- to an S017 row would violate the self-FK at S014's commit (the deferred check
-- only spans a single transaction/changeset). Stays L4. Year follows the new
-- parent (2026); the stale year inherited from the old parent (Oliy hamshiralik
-- ishi 60911200 → 2023, added by S015's L4-inheritance block) is cleared.
-- Idempotent; rollback reverts the parent first (see rollback file).
-- ---------------------------------------------------------------------------
UPDATE h_speciality
   SET parent_id = '2430d4df-7d95-5bf6-ac29-53ddfdc99814', updated_by = 'curation'
 WHERE id = 'c470f50d-4a5f-a925-3881-56ad2db91745';
DELETE FROM h_speciality_year WHERE speciality_id = 'c470f50d-4a5f-a925-3881-56ad2db91745';
INSERT INTO h_speciality_year (speciality_id, year) VALUES
  ('c470f50d-4a5f-a925-3881-56ad2db91745', 2026)
ON CONFLICT (speciality_id, year) DO NOTHING;
