-- =====================================================
-- S042: Ordinatura specialities (h_speciality + h_speciality_year)
-- =====================================================
-- Source: docs/klassifikator/hemishe_h_speciality_ordinatura.xlsx — the ministry's export of the
--         frozen CUBA table `hemishe_h_speciality_ordinatura` (69 live rows, all 8-digit 8091*).
--         Generated by domain/etl/speciality/generate_s042_ordinatura.py — DO NOT hand-edit,
--         re-run the ETL.
-- Scope:  the classifier stops being bachelor+master only. education_type = '13' (Ordinatura),
--         already seeded by V022 and admitted by the CHECK that M017 widens immediately before
--         this changeset — M017 MUST stay ordered above S042 or every INSERT below fails 23514.
-- Rows:   69, not the 70 the live legacy table holds. The 70th (7b2f1cec…,
--         code 17.00.09 'Raqs sanʼati') is a stray: its _parent points outside the ordinatura
--         table and its code uses the scientific-degree NN.NN.NN shape rather than the 8-digit
--         classifier shape. The ministry's xlsx omits it and so does this seed.
-- Tree:   71 rows, not 69 — the two ancestor categories are cloned for education_type '13':
--             900000 SOGʻLIQNI SAQLASH VA IJTIMOIY TAʼMINOT   (L1, parent NULL)
--               └─ 910000 Sogʻliqni saqlash                   (L2)
--                    └─ the 69 imported specialities          (L3)
--         Every education type in this table already keeps its OWN complete copy of the tree:
--         Bakalavr and Magistr each have 18 L1 + 59 L2 rows carrying identical codes and different
--         ids (900000 = a3796ec1 for '11' and ae3b0823 for '12'; 910000 = 960be177 and 1f1187c0).
--         This is the third copy of the one branch ordinatura needs, with names, review status and
--         audit flags taken verbatim from those twins.
--         Why not simply reuse 960be177, the Bakalavr 910000 that 18 of the source rows already
--         name as their _parent? Because in the LEGACY schema that is the only value possible —
--         hemishe_h_speciality_ordinatura._parent has an FK onto hemishe_h_speciality_bachelor(id)
--         and CUBA types the field as HSpecialityBachelor — while in the unified classifier
--         getTree() filters by education type and surfaces a node whose parent is outside the
--         filtered set AS A ROOT. A '11' parent therefore rendered the Ordinatura view as 69 flat
--         rows with no hierarchy at all. Cloning also restores the invariant that held across all
--         5603 pre-existing rows: a child's education_type always equals its parent's.
--         Anything that ever syncs ordinatura back into the legacy table must translate this L2 id
--         to 960be177 — LegacySpecialitySyncService covers '11'/'12' only and does not touch these.
-- Year:   2023 for all 71, ancestors included. The legacy _year column is empty and this
--         classifier requires years (S015 header), so the edition year is supplied here; every one
--         of the 36 L1 and 118 L2 rows already in the table carries at least one year, so the two
--         new categories must too. 2023 rather than the twins' 2021 because that is when this
--         branch enters the classifier — and the year filter prunes on descendants anyway (a branch
--         survives iff it has a surviving child). The S015 parent-year backfill only touches
--         hierarchy_level 4, so it never reaches any of these rows.
-- id:     the legacy UUID verbatim. LegacySpecialitySyncService bridges h_speciality back into the
--         frozen hemishe_h_speciality_* tables BY UUID, so reusing the legacy id keeps that bridge
--         and any existing reference pointing at one row instead of forking it into two.
-- is_checked: the source value (35 of the 69 are true) — unlike S014/S017 rows, which are born
--         false. These are copied verbatim from a table CUBA and Univer already serve; flipping
--         the flag would make the two copies disagree for no reason.
-- ROW VERSION: -1 (ministry instruction), which is this table's own baseline rather than an
--         oddity — 5512 of the 5603 pre-existing rows carry -1, including all four ancestor twins.
--         The higher values are the handful of rows edited through the UI since (60 at 1, 41 at 2,
--         11 at 3, ...), because @Version increments from wherever a row starts. Inserting at 1
--         would have made every imported row look as if it had already been curated once. A
--         negative seed is fine for optimistic locking: the first edit writes 0, then 1, 2, ...
-- review_status APPROVED (official ministry classifier, like S014/S017) => distributable. A seed
--         INSERT does not push: only HSpecialityService.update() emits an outbox event.
-- name_uz: apostrophes folded to the project-standard letters (oʻ/gʻ = U+02BB, ʼ = U+02BC), as in
--         S014/S017. Cosmetic for identity — h_speciality_fold() maps every variant to a space.
-- name_oz: NULL for all 69 — the source carries a Russian column and no Uzbek-Cyrillic one.
-- CORRECTION (documented, one row): 19d8acc7 (80910725 Parodontologiya) carried the ENGLISH word
--         'Periodontology' in name_ru with name_en empty. English text in the Russian column
--         renders as English to a Russian reader, so it is moved to name_en and name_ru left NULL.
--         Nothing is lost — that value was never Russian.
-- Duplicated codes are legal and intentional: 80910714 and 80910715 each name two different
--         specialities in the source. uq_h_speciality_identity is (education_type, code,
--         name_search), so both members of each pair are distinct rows.
-- Idempotent: ON CONFLICT (id) DO NOTHING never overwrites a later FE edit; the year rows use
--         ON CONFLICT (speciality_id, year) DO NOTHING.
-- Additive: hemishe_h_speciality_ordinatura and the 175/175 legacy contract are NOT touched.
-- =====================================================

INSERT INTO h_speciality (id,code,name_uz,name_oz,name_ru,name_en,education_type,review_status,parent_id,hierarchy_level,active,is_checked,version) VALUES
  -- Ancestor categories, cloned for education_type '13' (see the Tree note above)
  ('64bcaf9e-2bff-5027-beb6-dd92b1d51699','900000','SOGʻLIQNI SAQLASH VA IJTIMOIY TAʼMINOT',NULL,NULL,NULL,'13','APPROVED',NULL,1,true,false,-1),
  ('1bb702e2-05f1-5312-b5ff-c084ceb1ef6d','910000','Sogʻliqni saqlash',NULL,NULL,NULL,'13','APPROVED','64bcaf9e-2bff-5027-beb6-dd92b1d51699',2,true,false,-1),
  -- The 69 imported specialities
  ('8c3b1dc7-38ce-4ddf-8621-9a291d2a2a06','80910101','Stomatologiya',NULL,'Стоматология','Dentistry','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('302dcfa1-4a61-175c-7303-47a05149fa4b','80910201','Akusherlik va ginekologiya',NULL,'Акушерство и гинекология','Obstetrics and gynecology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('ee3ff12a-232d-4b7b-a992-6dc64438f418','80910202','Endokrinologiya',NULL,'Эндокринология','Endocrinology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('df7d962d-84f8-4ba6-9363-bc8287195735','80910203','Terapiya',NULL,'Терапия','Therapy','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('5ebd720b-4536-4a43-b7dc-fb275971b343','80910204','Otorinolaringologiya',NULL,'Оториноларингология','Otorhinolaryngology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('9929aa55-45cb-43a5-b51e-135e46866fc2','80910205','Kardiologiya',NULL,'Кардиология','Cardiology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('3416f56d-506b-4eed-b912-428bc8f88e25','80910206','Oftalmologiya',NULL,'Офтальмология','Ophthalmology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('e585b5d2-7e1e-4bda-a1b8-a29f2b6bb1e6','80910207','Yuqumli kasalliklar',NULL,'Инфекционные заболевания','Infectious diseases','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('a11ae9c2-d890-402d-93c0-61263955c276','80910208','Dermatovenerologiya',NULL,'Дерматовенерология','Dermatovenereology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('887635fd-5137-49f8-9887-7c14d88aa48c','80910209','Nevrologiya',NULL,'Неврология','Neurology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('f5101799-3c81-4c02-8506-fa45621887ca','80910210','Umumiy onkologiya',NULL,'Общая онкология','General oncology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('c876eff8-93dc-4634-bc1d-0a857516d8b2','80910211','Psixiatriya',NULL,'Психиатрия','Psychiatry','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('d32199eb-19ff-4899-ad1f-ef37cc780e9f','80910212','Umumiy xirurgiya',NULL,'Общая хирургия','General surgery','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('00cf5c05-d065-42ca-b71e-6c57984fcd7a','80910214','Nevroxirurgiya',NULL,'Нейрохирургия','Neurosurgery','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('02a47b89-7ce2-480e-8349-2d56c46e665e','80910217','Urologiya',NULL,'Урология','Urology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('bac04ea6-708b-4211-80f2-d5f8798e3520','80910219','Narkologiya',NULL,'Наркология','Narcology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('bf22e55f-ecfa-4415-9921-5e6845c16514','80910220','Anesteziologiya va reanimatologiya',NULL,'Анестезиология и реаниматология','Anesthesiology and resuscitation','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('e623bb7a-7217-4c4e-a991-a7ec4021dc78','80910221','Travmatologiya va ortopediya',NULL,'Травматология и ортопедия','Traumatology and Orthopedics','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('a5da9708-1c4b-40e0-9641-350511b45c92','80910222','Sud tibbiyoti ekspertizasi',NULL,'Судебно-медицинская экспертиза','Forensic-medical examination','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('df5b4ed6-1aa3-4d0a-a828-07acd502f495','80910223','Patologik anatomiya',NULL,'Патологическая анатомия','pathological anatomy','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('e701da7d-eec3-42a4-a8a8-f77c00a14541','80910226','Gematologiya va transfuziologiya',NULL,'Гематология и трансфузиология','Hematology and transfusiology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('44aa2483-2136-4c85-b321-2d90102169d6','80910227','Tibbiy radiologiya',NULL,'Медицинская радиология','Medical Radiology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('8e7c5e46-c7be-475f-b278-eb7ee75b4f90','80910228','Ftiziatriya',NULL,'Фтизиатрия','Phthisiology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('59c80cb8-5946-d5c1-2560-b3dd01c1608c','80910230','Tibbiy genetika',NULL,NULL,'Medical genetics','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('903a2269-de8e-4e5e-ae83-5d2910438db0','80910232','Allergologiya va klinik immunologiya',NULL,'Аллергология и клиническая иммунология','Allergology and Clinical Immunology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('0dfe4f19-5cd0-43b1-90c3-362e3804a84e','80910233','Pulmonologiya',NULL,'Пульмонология','Pulmonology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('cec4bfa7-bfb3-28bf-91c5-c951eed0c635','80910234','Morfologiya',NULL,NULL,'Morphology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('2b56f125-74e8-2292-5b8a-d4063d81f06f','80910275','Bolalar kardiorevmatologiyasi',NULL,'Детская кардиоревматология','Pediatric cardiorheumatology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('e4e1572c-0896-4940-b8b9-bb0b64891f5a','80910301','Pediatriya',NULL,'Педиатрия','Pediatrics','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('7ecd715d-b4ce-4c80-9957-0cd7e7f3c118','80910302','Bolalar xirurgiyasi',NULL,'Детская хирургия','Pediatric surgery','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('48af35e2-7eeb-421f-b1af-e8a9f6664265','80910303','Bolalar anesteziologiya va reanimatologiyasi',NULL,'Детская анестезиология и реаниматология','Pediatric anesthesiology and resuscitation','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('eb8beb28-e91a-4f5b-b06c-5990d127ac41','80910305','Bolalar nevrologiyasi',NULL,'Детская неврология','Pediatric neurology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('6efa73e2-a262-4c30-8661-2c7f3c860644','80910306','Neonatologiya',NULL,'Неонатология','Neonatology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('a821f9cb-1939-4362-9103-f5a3020f37cc','80910307','Bolalar va oʻsmir qizlar ginekologiyasi',NULL,'Гинекология детей и девочек-подростков','Gynecology of children and adolescent girls','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('88d16660-d024-4b3f-a170-80cb6b6f122d','80910310','Bolalar yuqumli kasalliklari',NULL,'Инфекционные болезни детей','Infectious diseases of children','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('026f7585-f6e5-4dc2-9a6d-a605c9d50359','80910401','Gigiena',NULL,'Гигиена','Hygiene','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('057d58a7-7c22-4fba-b09f-97c890e53fa3','80910403','Epidemiologiya',NULL,'Эпидемиология','Epidemiology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('f85beec3-f83d-4b59-939b-a52861a84ab1','80910601','Laboratoriya ishi',NULL,'Лабораторная работа','Laboratory work','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,true,-1),
  ('2c529dc8-8a86-0c31-2916-b36c68a1e94a','80910700','Bolalar nefrologiyasi gemodializ bilan',NULL,'Детская нефрология с гемодиализом','Pediatric nephrology with hemodialysis','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('d5e0254d-a8ed-df1d-3f99-14cf8914746e','80910701','Bolalar terapevtik stomatologiyasi',NULL,'Детская терапевтическая стоматология','Pediatric therapeutic dentistry','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('4486cc8d-bdd8-fc9c-136e-3e7191a98d8e','80910702','Bolalar xirurgik stomatologiyasi',NULL,'Детская хирургическая стоматология','Pediatric Surgical Dentistry','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('05630311-b725-c23d-a754-3c8d117609fd','80910703','Dental impantologiya',NULL,'Дентальная имплантология','Dental implantology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('17d19bb7-fb2b-d37c-298e-565add1527d5','80910704','Nefrologiya gemodializ bilan',NULL,'Нефрология с гемодиализом','Nephrology with hemodialysis','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('783ebc94-45cc-3977-3d5a-9675c7a502f4','80910705','Ortodontiya',NULL,'Ортодонтия','Orthodontics','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('1f492904-ce78-9a36-6e0a-5e8706006bb4','80910706','Ortopedik stomatologiya',NULL,'Ортопедическая стоматология','Orthopedic dentistry','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('f40b490d-f1b7-173e-80ce-c540547a1188','80910707','Revmatologiya',NULL,'Ревматология','Rheumatology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('355ecf60-005e-4900-7e61-fe48d130fdc8','80910708','Terapevtik stomatologiya',NULL,'Терапевтическая стоматология','Therapeutic dentistry','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('0248ad1f-6f1d-c35a-3f37-5fd84c713a72','80910709','Xirurgik stomatologiya',NULL,'Хирургическая стоматология','Surgical dentistry','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('dff37fc0-ce33-6099-a8c2-b2262dfd7209','80910710','Yuz-jagʻ xirurgiyasi',NULL,'Челюстно-лицевая хирургия','Maxillofacial surgery','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('f536e2a4-339c-2a16-16ba-eef9d73bdf09','80910711','Mehnat gigiyenasi',NULL,NULL,'Occupational hygiene','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('25471de9-0883-e51e-6351-09e49800456b','80910712','Nutritsiologiya',NULL,NULL,'Nutriciology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('9fe017f8-b1ae-11bc-aa9e-6e156a423412','80910713','Shoshilinch tibbiy yordam',NULL,NULL,'Emergency medical care','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('a4f1d775-eb07-37cf-92c1-e0e672d83209','80910714','Bolalar va oʻsmirlar gigiyenasi',NULL,NULL,'Hygiene of children and adolescents','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('fafc7057-0ecc-0294-d5e3-15b4a6e41f40','80910714','Shoshilinch xolat',NULL,NULL,'Emergency','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('649d72a7-361c-551a-dd5f-6f1462e8b833','80910715','Kasb kasalliklari',NULL,NULL,NULL,'13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('54b099be-7c60-238e-fab7-63ed14a6888b','80910715','Kommunal gigiyenasi',NULL,NULL,'Сommunal hygiene','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('234ab11c-391a-223b-3cb5-efedfbf23dbb','80910716','Plastik xirurgiya',NULL,NULL,NULL,'13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('6c6443c3-1c9b-3f7e-54bb-d4c6287f1907','80910717','Reabilitologiya',NULL,NULL,NULL,'13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('f279fd6c-d5f1-a1ea-eba5-a53c3c999d87','80910718','Sport tibbiyoti',NULL,NULL,NULL,'13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('bb1ac3d1-d3ed-c2ca-0d68-6d9707bc1a4d','80910719','Tibbiy psixologiya',NULL,NULL,NULL,'13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('55898bc3-2fbd-f0b6-4795-4e55a530abfc','80910720','Xirurgiya',NULL,NULL,NULL,'13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('ca7e1e1e-f07b-c274-a07d-62f56f01a77f','80910721','Ichki kasalliklar',NULL,NULL,NULL,'13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('40477745-09c8-ac6d-8c6f-b1e22b76c53f','80910722','Klinik farmakologiya',NULL,NULL,NULL,'13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('a7f2ff12-f8dd-1c27-f55b-eae300b10e01','80910723','Gastroenterologiya',NULL,NULL,NULL,'13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('e8ef478b-8fa1-0cad-551a-0759e527f81c','80910724','Yurak-qon tomir xirurgiyasi',NULL,NULL,NULL,'13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('19d8acc7-6250-adfd-6e39-0c1cc2e9966b','80910725','Parodontologiya',NULL,NULL,'Periodontology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('c2beadd7-7c7d-29c0-b469-7a078ea7a112','80910726','Bolalar onkologiya-gematologiyasi',NULL,NULL,'Pediatric oncology-hematology','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('b70ea0ed-f3bc-2878-0f70-aa0b43eac237','80910727','Rentgen endovaskulyar xirurgiya',NULL,NULL,'X-ray endovascular surgery','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1),
  ('673a5360-9e74-23a0-c963-a62031387fb8','80910728','Qon-tomir xirurgiya',NULL,NULL,'Vascular Surgery','13','APPROVED','1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',3,true,false,-1)
ON CONFLICT (id) DO NOTHING;

-- Edition year 2023 for all 71 rows, the two ancestor categories included — every L1 and
-- L2 row already in this table carries at least one year, so these must too. Scoped to this
-- seed's own ids rather than "every education_type = '13' row", so a re-run never
-- stamps 2023 onto an ordinatura speciality a curator later added with a different year.
INSERT INTO h_speciality_year (speciality_id, year) VALUES
  ('64bcaf9e-2bff-5027-beb6-dd92b1d51699',2023),
  ('1bb702e2-05f1-5312-b5ff-c084ceb1ef6d',2023),
  ('8c3b1dc7-38ce-4ddf-8621-9a291d2a2a06',2023),
  ('302dcfa1-4a61-175c-7303-47a05149fa4b',2023),
  ('ee3ff12a-232d-4b7b-a992-6dc64438f418',2023),
  ('df7d962d-84f8-4ba6-9363-bc8287195735',2023),
  ('5ebd720b-4536-4a43-b7dc-fb275971b343',2023),
  ('9929aa55-45cb-43a5-b51e-135e46866fc2',2023),
  ('3416f56d-506b-4eed-b912-428bc8f88e25',2023),
  ('e585b5d2-7e1e-4bda-a1b8-a29f2b6bb1e6',2023),
  ('a11ae9c2-d890-402d-93c0-61263955c276',2023),
  ('887635fd-5137-49f8-9887-7c14d88aa48c',2023),
  ('f5101799-3c81-4c02-8506-fa45621887ca',2023),
  ('c876eff8-93dc-4634-bc1d-0a857516d8b2',2023),
  ('d32199eb-19ff-4899-ad1f-ef37cc780e9f',2023),
  ('00cf5c05-d065-42ca-b71e-6c57984fcd7a',2023),
  ('02a47b89-7ce2-480e-8349-2d56c46e665e',2023),
  ('bac04ea6-708b-4211-80f2-d5f8798e3520',2023),
  ('bf22e55f-ecfa-4415-9921-5e6845c16514',2023),
  ('e623bb7a-7217-4c4e-a991-a7ec4021dc78',2023),
  ('a5da9708-1c4b-40e0-9641-350511b45c92',2023),
  ('df5b4ed6-1aa3-4d0a-a828-07acd502f495',2023),
  ('e701da7d-eec3-42a4-a8a8-f77c00a14541',2023),
  ('44aa2483-2136-4c85-b321-2d90102169d6',2023),
  ('8e7c5e46-c7be-475f-b278-eb7ee75b4f90',2023),
  ('59c80cb8-5946-d5c1-2560-b3dd01c1608c',2023),
  ('903a2269-de8e-4e5e-ae83-5d2910438db0',2023),
  ('0dfe4f19-5cd0-43b1-90c3-362e3804a84e',2023),
  ('cec4bfa7-bfb3-28bf-91c5-c951eed0c635',2023),
  ('2b56f125-74e8-2292-5b8a-d4063d81f06f',2023),
  ('e4e1572c-0896-4940-b8b9-bb0b64891f5a',2023),
  ('7ecd715d-b4ce-4c80-9957-0cd7e7f3c118',2023),
  ('48af35e2-7eeb-421f-b1af-e8a9f6664265',2023),
  ('eb8beb28-e91a-4f5b-b06c-5990d127ac41',2023),
  ('6efa73e2-a262-4c30-8661-2c7f3c860644',2023),
  ('a821f9cb-1939-4362-9103-f5a3020f37cc',2023),
  ('88d16660-d024-4b3f-a170-80cb6b6f122d',2023),
  ('026f7585-f6e5-4dc2-9a6d-a605c9d50359',2023),
  ('057d58a7-7c22-4fba-b09f-97c890e53fa3',2023),
  ('f85beec3-f83d-4b59-939b-a52861a84ab1',2023),
  ('2c529dc8-8a86-0c31-2916-b36c68a1e94a',2023),
  ('d5e0254d-a8ed-df1d-3f99-14cf8914746e',2023),
  ('4486cc8d-bdd8-fc9c-136e-3e7191a98d8e',2023),
  ('05630311-b725-c23d-a754-3c8d117609fd',2023),
  ('17d19bb7-fb2b-d37c-298e-565add1527d5',2023),
  ('783ebc94-45cc-3977-3d5a-9675c7a502f4',2023),
  ('1f492904-ce78-9a36-6e0a-5e8706006bb4',2023),
  ('f40b490d-f1b7-173e-80ce-c540547a1188',2023),
  ('355ecf60-005e-4900-7e61-fe48d130fdc8',2023),
  ('0248ad1f-6f1d-c35a-3f37-5fd84c713a72',2023),
  ('dff37fc0-ce33-6099-a8c2-b2262dfd7209',2023),
  ('f536e2a4-339c-2a16-16ba-eef9d73bdf09',2023),
  ('25471de9-0883-e51e-6351-09e49800456b',2023),
  ('9fe017f8-b1ae-11bc-aa9e-6e156a423412',2023),
  ('a4f1d775-eb07-37cf-92c1-e0e672d83209',2023),
  ('fafc7057-0ecc-0294-d5e3-15b4a6e41f40',2023),
  ('649d72a7-361c-551a-dd5f-6f1462e8b833',2023),
  ('54b099be-7c60-238e-fab7-63ed14a6888b',2023),
  ('234ab11c-391a-223b-3cb5-efedfbf23dbb',2023),
  ('6c6443c3-1c9b-3f7e-54bb-d4c6287f1907',2023),
  ('f279fd6c-d5f1-a1ea-eba5-a53c3c999d87',2023),
  ('bb1ac3d1-d3ed-c2ca-0d68-6d9707bc1a4d',2023),
  ('55898bc3-2fbd-f0b6-4795-4e55a530abfc',2023),
  ('ca7e1e1e-f07b-c274-a07d-62f56f01a77f',2023),
  ('40477745-09c8-ac6d-8c6f-b1e22b76c53f',2023),
  ('a7f2ff12-f8dd-1c27-f55b-eae300b10e01',2023),
  ('e8ef478b-8fa1-0cad-551a-0759e527f81c',2023),
  ('19d8acc7-6250-adfd-6e39-0c1cc2e9966b',2023),
  ('c2beadd7-7c7d-29c0-b469-7a078ea7a112',2023),
  ('b70ea0ed-f3bc-2878-0f70-aa0b43eac237',2023),
  ('673a5360-9e74-23a0-c963-a62031387fb8',2023)
ON CONFLICT (speciality_id, year) DO NOTHING;

-- Verification: report, never fail. A shortfall means rows pre-existed under a different id
-- (an FE-created duplicate) — worth a look, but not a reason to abort a migration. The orphan
-- check is the one that matters: it is what was wrong before the ancestors existed, and a
-- non-zero count means the Ordinatura view has gone back to rendering a flat list.
DO $$
DECLARE
    spec_count   INTEGER;
    year_count   INTEGER;
    orphan_count INTEGER;
BEGIN
    SELECT count(*) INTO spec_count FROM h_speciality WHERE education_type = '13';
    SELECT count(*) INTO year_count
      FROM h_speciality_year y
      JOIN h_speciality s ON s.id = y.speciality_id
     WHERE s.education_type = '13' AND y.year = 2023;
    SELECT count(*) INTO orphan_count
      FROM h_speciality c
      LEFT JOIN h_speciality p ON p.id = c.parent_id
     WHERE c.education_type = '13'
       AND c.parent_id IS NOT NULL
       AND (p.id IS NULL OR p.education_type <> c.education_type);
    RAISE NOTICE 'S042: ordinatura qatorlari = %, 2023 yil bogʻlami = % (kutilgan: 71)',
        spec_count, year_count;
    IF spec_count < 71 THEN
        RAISE NOTICE 'S042 OGOHLANTIRISH: 71 ta kutilgan edi, % ta topildi', spec_count;
    END IF;
    IF orphan_count > 0 THEN
        RAISE NOTICE 'S042 OGOHLANTIRISH: % ta ordinatura qatorining otasi boshqa taʼlim turida — daraxt tekis chiqadi', orphan_count;
    END IF;
END $$;
