## Migration-only profil
## Web server ishga tushmaydi, faqat Liquibase migration ishlaydi.
## Helm pre-upgrade Job bu profil bilan ishga tushadi.
spring:
  main:
    web-application-type: none
  liquibase:
    enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    master:
      hikari:
        data-source-properties:
          socketTimeout: 600
        leak-detection-threshold: 0
