## Migration-only profil
## Web server ishga tushmaydi, faqat Liquibase migration ishlaydi.
## Helm pre-upgrade Job bu profil bilan ishga tushadi.
spring:
  main:
    web-application-type: none
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
  datasource:
    master:
      hikari:
        data-source-properties:
          socketTimeout: 600
        leak-detection-threshold: 0
