-- V013 rollback — dependency reverse tartibida
DROP TABLE IF EXISTS user_favorite CASCADE;
DROP FUNCTION IF EXISTS upsert_menu(UUID, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, INTEGER, UUID, VARCHAR) CASCADE;
DROP FUNCTION IF EXISTS update_menu_updated_at() CASCADE;
DROP TABLE IF EXISTS menu CASCADE;
