package uz.hemis.service.menu;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import uz.hemis.service.menu.dto.MenuItem;

import java.util.Arrays;
import java.util.List;

/**
 * Menu Configuration
 * Migrated from old-hemis CUBA application (web-menu.xml)
 *
 * @author System Architect
 * @version 2.0
 */
@Configuration
public class MenuConfig {

    @Bean
    public List<MenuItem> menuStructure() {
        return Arrays.asList(
            // 1. Dashboard
            createDashboard(),

            // 2. Registry (Reestlar)
            createRegistry(),

            // 3. Rating (Reyting)
            createRating(),

            // 4. Data Management (Application)
            createDataManagement(),

            // 5. Reports
            createReports(),

            // 6. System
            createSystem()
        );
    }

    /**
     * Dashboard Menu
     */
    private MenuItem createDashboard() {
        return MenuItem.builder()
            .id("dashboard")
            .label("menu.dashboard")  // Translation key for i18n
            .url("/dashboard")
            .icon("home")
            .permission("dashboard.view")
            .active(true)
            .order(1)
            .build();
    }

    /**
     * Registry Menu (Reestlar)
     */
    private MenuItem createRegistry() {
        return MenuItem.builder()
            .id("registry")
            .label("menu.registry")  // Translation key for i18n
            .url("/registry")
            .icon("database")
            .permission("registry.view")
            .active(true)
            .order(2)
            .items(Arrays.asList(
                MenuItem.builder()
                    .id("registry-e-reestr")
                    .label("menu.registry.e_reestr")
                    .url("/registry/e-reestr")
                    .icon("database")
                    .permission("registry.e-reestr.view")
                    .active(true)
                    .order(1)
                    .items(Arrays.asList(
                        MenuItem.builder()
                            .id("registry-e-reestr-university")
                            .label("menu.registry.e_reestr.university")
                            .url("/registry/e-reestr/university")
                            .icon("building")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(1)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-faculty")
                            .label("menu.registry.e_reestr.faculty")
                            .url("/registry/e-reestr/faculty")
                            .icon("school")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(2)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-cathedra")
                            .label("menu.registry.e_reestr.cathedra")
                            .url("/registry/e-reestr/cathedra")
                            .icon("users")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(3)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-teacher")
                            .label("menu.registry.e_reestr.teacher")
                            .url("/registry/e-reestr/teacher")
                            .icon("user-check")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(4)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-student")
                            .label("menu.registry.e_reestr.student")
                            .url("/registry/e-reestr/student")
                            .icon("graduation-cap")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(5)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-diploma")
                            .label("menu.registry.e_reestr.diploma")
                            .url("/registry/e-reestr/diploma")
                            .icon("award")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(6)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-speciality-bachelor")
                            .label("menu.registry.e_reestr.speciality_bachelor")
                            .url("/registry/e-reestr/speciality-bachelor")
                            .icon("book-open")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(7)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-speciality-master")
                            .label("menu.registry.e_reestr.speciality_master")
                            .url("/registry/e-reestr/speciality-master")
                            .icon("book-open")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(8)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-speciality-doctoral")
                            .label("menu.registry.e_reestr.speciality_doctoral")
                            .url("/registry/e-reestr/speciality-doctoral")
                            .icon("book-open")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(9)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-employee-jobs")
                            .label("menu.registry.e_reestr.employee_jobs")
                            .url("/registry/e-reestr/employee-jobs")
                            .icon("briefcase")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(10)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-diploma-blank-distribution")
                            .label("menu.registry.e_reestr.diploma_blank_distribution")
                            .url("/registry/e-reestr/diploma-blank-distribution")
                            .icon("file-text")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(11)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-diploma-blank")
                            .label("menu.registry.e_reestr.diploma_blank")
                            .url("/registry/e-reestr/diploma-blank")
                            .icon("file-text")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(12)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-speciality-ordinatura")
                            .label("menu.registry.e_reestr.speciality_ordinatura")
                            .url("/registry/e-reestr/speciality-ordinatura")
                            .icon("book")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(13)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-university-speciality")
                            .label("menu.registry.e_reestr.university_speciality")
                            .url("/registry/e-reestr/university-speciality")
                            .icon("layers")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(14)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-university-group")
                            .label("menu.registry.e_reestr.university_group")
                            .url("/registry/e-reestr/university-group")
                            .icon("users")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(15)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-student-scholarship")
                            .label("menu.registry.e_reestr.student_scholarship")
                            .url("/registry/e-reestr/student-scholarship")
                            .icon("dollar-sign")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(16)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-student-certificate")
                            .label("menu.registry.e_reestr.student_certificate")
                            .url("/registry/e-reestr/student-certificate")
                            .icon("award")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(17)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-employee-certificate")
                            .label("menu.registry.e_reestr.employee_certificate")
                            .url("/registry/e-reestr/employee-certificate")
                            .icon("award")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(18)
                            .build(),
                        MenuItem.builder()
                            .id("registry-e-reestr-student-lite")
                            .label("menu.registry.e_reestr.student_lite")
                            .url("/registry/e-reestr/student-lite")
                            .icon("user")
                            .permission("registry.e-reestr.view")
                            .active(true)
                            .order(19)
                            .build()
                    ))
                    .build(),
                MenuItem.builder()
                    .id("registry-scientific")
                    .label("menu.registry.scientific")  // Translation key for i18n
                    .url("/registry/scientific")
                    .icon("graduation-cap")
                    .permission("registry.scientific.view")
                    .active(true)
                    .order(2)
                    .items(Arrays.asList(
                        MenuItem.builder().id("registry-scientific-doctorate").label("menu.registry.scientific.doctorate").url("/registry/scientific/doctorate").icon("user-graduate").permission("registry.scientific.view").active(true).order(1).build(),
                        MenuItem.builder().id("registry-scientific-dissertation").label("menu.registry.scientific.dissertation").url("/registry/scientific/dissertation").icon("file-text").permission("registry.scientific.view").active(true).order(2).build(),
                        MenuItem.builder().id("registry-scientific-project").label("menu.registry.scientific.project").url("/registry/scientific/project").icon("lightbulb").permission("registry.scientific.view").active(true).order(3).build(),
                        MenuItem.builder().id("registry-scientific-executor").label("menu.registry.scientific.executor").url("/registry/scientific/executor").icon("users").permission("registry.scientific.view").active(true).order(4).build(),
                        MenuItem.builder().id("registry-scientific-project-meta").label("menu.registry.scientific.project_meta").url("/registry/scientific/project-meta").icon("dollar-sign").permission("registry.scientific.view").active(true).order(5).build(),
                        MenuItem.builder().id("registry-scientific-publication").label("menu.registry.scientific.publication").url("/registry/scientific/publication").icon("book").permission("registry.scientific.view").active(true).order(6).build(),
                        MenuItem.builder().id("registry-scientific-methodical").label("menu.registry.scientific.methodical").url("/registry/scientific/methodical").icon("book-open").permission("registry.scientific.view").active(true).order(7).build(),
                        MenuItem.builder().id("registry-scientific-property").label("menu.registry.scientific.property").url("/registry/scientific/property").icon("briefcase").permission("registry.scientific.view").active(true).order(8).build(),
                        MenuItem.builder().id("registry-scientific-author").label("menu.registry.scientific.author").url("/registry/scientific/author").icon("edit").permission("registry.scientific.view").active(true).order(9).build(),
                        MenuItem.builder().id("registry-scientific-activity").label("menu.registry.scientific.activity").url("/registry/scientific/activity").icon("activity").permission("registry.scientific.view").active(true).order(10).build()
                    ))
                    .build(),
                MenuItem.builder()
                    .id("registry-student-meta")
                    .label("menu.registry.student_meta")  // Translation key for i18n
                    .url("/registry/student-meta")
                    .icon("user-circle")
                    .permission("registry.student-meta.view")
                    .active(true)
                    .order(3)
                    .build()
            ))
            .build();
    }

    /**
     * Rating Menu (Reyting)
     */
    private MenuItem createRating() {
        return MenuItem.builder()
            .id("rating")
            .label("menu.rating")
            .url("/rating")
            .icon("line-chart")
            .permission("rating.view")
            .active(true)
            .order(3)
            .items(Arrays.asList(
                // Administrative Rating
                MenuItem.builder()
                    .id("rating-administrative")
                    .label("menu.rating.administrative")
                    .url("/rating/administrative")
                    .icon("building")
                    .permission("rating.administrative.view")
                    .active(true)
                    .order(1)
                    .items(Arrays.asList(
                        MenuItem.builder()
                            .id("rating-administrative-employee")
                            .label("menu.rating.administrative.employee")
                            .url("/rating/administrative/employee")
                            .icon("users")
                            .permission("rating.administrative.employee.view")
                            .active(true)
                            .order(1)
                            .build(),
                        MenuItem.builder()
                            .id("rating-administrative-students")
                            .label("menu.rating.administrative.students")
                            .url("/rating/administrative/students")
                            .icon("graduation-cap")
                            .permission("rating.administrative.students.view")
                            .active(true)
                            .order(2)
                            .build(),
                        MenuItem.builder()
                            .id("rating-administrative-sport")
                            .label("menu.rating.administrative.sport")
                            .url("/rating/administrative/sport")
                            .icon("trophy")
                            .permission("rating.administrative.sport.view")
                            .active(true)
                            .order(3)
                            .build()
                    ))
                    .build(),

                // Academic Rating
                MenuItem.builder()
                    .id("rating-academic")
                    .label("menu.rating.academic")
                    .url("/rating/academic")
                    .icon("layout-dashboard")
                    .permission("rating.academic.view")
                    .active(true)
                    .order(2)
                    .items(Arrays.asList(
                        MenuItem.builder()
                            .id("rating-academic-methodical")
                            .label("menu.rating.academic.methodical")
                            .url("/rating/academic/methodical")
                            .icon("book")
                            .permission("rating.academic.methodical.view")
                            .active(true)
                            .order(1)
                            .build(),
                        MenuItem.builder()
                            .id("rating-academic-study")
                            .label("menu.rating.academic.study")
                            .url("/rating/academic/study")
                            .icon("book")
                            .permission("rating.academic.study.view")
                            .active(true)
                            .order(2)
                            .build(),
                        MenuItem.builder()
                            .id("rating-academic-verification")
                            .label("menu.rating.academic.verification")
                            .url("/rating/academic/verification")
                            .icon("shield-check")
                            .permission("rating.academic.verification.view")
                            .active(true)
                            .order(3)
                            .build()
                    ))
                    .build(),

                // Scientific Rating
                MenuItem.builder()
                    .id("rating-scientific")
                    .label("menu.rating.scientific")
                    .url("/rating/scientific")
                    .icon("graduation-cap")
                    .permission("rating.scientific.view")
                    .active(true)
                    .order(3)
                    .items(Arrays.asList(
                        MenuItem.builder()
                            .id("rating-scientific-publications")
                            .label("menu.rating.scientific.publications")
                            .url("/rating/scientific/publications")
                            .icon("send")
                            .permission("rating.scientific.publications.view")
                            .active(true)
                            .order(1)
                            .build(),
                        MenuItem.builder()
                            .id("rating-scientific-projects")
                            .label("menu.rating.scientific.projects")
                            .url("/rating/scientific/projects")
                            .icon("lightbulb")
                            .permission("rating.scientific.projects.view")
                            .active(true)
                            .order(2)
                            .build(),
                        MenuItem.builder()
                            .id("rating-scientific-intellectual")
                            .label("menu.rating.scientific.intellectual")
                            .url("/rating/scientific/intellectual")
                            .icon("settings")
                            .permission("rating.scientific.intellectual.view")
                            .active(true)
                            .order(3)
                            .build()
                    ))
                    .build(),

                // Student GPA
                MenuItem.builder()
                    .id("rating-student-gpa")
                    .label("menu.rating.student_gpa")
                    .url("/rating/student-gpa")
                    .icon("award")
                    .permission("rating.student-gpa.view")
                    .active(true)
                    .order(4)
                    .build()
            ))
            .build();
    }

    /**
     * Data Management Menu (Application)
     */
    private MenuItem createDataManagement() {
        return MenuItem.builder()
            .id("data")
            .label("menu.data")
            .url("/data")
            .icon("database")
            .permission("data.view")
            .active(true)
            .order(4)
            .items(Arrays.asList(
                MenuItem.builder()
                    .id("data-general")
                    .label("menu.data.general")
                    .url("/data/general")
                    .icon("file-text")
                    .permission("data.general.view")
                    .active(true)
                    .order(1)
                    .items(Arrays.asList(
                        MenuItem.builder().id("data-general-country").label("menu.data.general.country").url("/data/general/country").icon("globe").permission("data.general.view").active(true).order(1).build(),
                        MenuItem.builder().id("data-general-soato").label("menu.data.general.soato").url("/data/general/soato").icon("map").permission("data.general.view").active(true).order(2).build(),
                        MenuItem.builder().id("data-general-nationality").label("menu.data.general.nationality").url("/data/general/nationality").icon("flag").permission("data.general.view").active(true).order(3).build(),
                        MenuItem.builder().id("data-general-citizenship").label("menu.data.general.citizenship").url("/data/general/citizenship").icon("passport").permission("data.general.view").active(true).order(4).build(),
                        MenuItem.builder().id("data-general-gender").label("menu.data.general.gender").url("/data/general/gender").icon("user").permission("data.general.view").active(true).order(5).build(),
                        MenuItem.builder().id("data-general-bachelor-specialty").label("menu.data.general.bachelor_specialty").url("/data/general/bachelor-specialty").icon("graduation-cap").permission("data.general.view").active(true).order(6).build(),
                        MenuItem.builder().id("data-general-master-specialty").label("menu.data.general.master_specialty").url("/data/general/master-specialty").icon("award").permission("data.general.view").active(true).order(7).build(),
                        MenuItem.builder().id("data-general-doctoral-specialty").label("menu.data.general.doctoral_specialty").url("/data/general/doctoral-specialty").icon("book-open").permission("data.general.view").active(true).order(8).build(),
                        MenuItem.builder().id("data-general-terrain").label("menu.data.general.terrain").url("/data/general/terrain").icon("home").permission("data.general.view").active(true).order(9).build(),
                        MenuItem.builder().id("data-general-poverty-level").label("menu.data.general.poverty_level").url("/data/general/poverty-level").icon("trending-down").permission("data.general.view").active(true).order(10).build()
                    ))
                    .build(),
                MenuItem.builder()
                    .id("data-structure")
                    .label("menu.data.structure")
                    .url("/data/structure")
                    .icon("share-2")
                    .permission("data.structure.view")
                    .active(true)
                    .order(2)
                    .items(Arrays.asList(
                        MenuItem.builder()
                            .id("data-structure-university-type")
                            .label("menu.data.structure.university_type")
                            .url("/data/structure/university-type")
                            .icon("building")
                            .permission("data.structure.view")
                            .active(true)
                            .order(1)
                            .build(),
                        MenuItem.builder()
                            .id("data-structure-ownership")
                            .label("menu.data.structure.ownership")
                            .url("/data/structure/ownership")
                            .icon("building")
                            .permission("data.structure.view")
                            .active(true)
                            .order(2)
                            .build(),
                        MenuItem.builder()
                            .id("data-structure-department-type")
                            .label("menu.data.structure.department_type")
                            .url("/data/structure/department-type")
                            .icon("building-2")
                            .permission("data.structure.view")
                            .active(true)
                            .order(3)
                            .build(),
                        MenuItem.builder()
                            .id("data-structure-locality-type")
                            .label("menu.data.structure.locality_type")
                            .url("/data/structure/locality-type")
                            .icon("map-pin")
                            .permission("data.structure.view")
                            .active(true)
                            .order(4)
                            .build(),
                        MenuItem.builder()
                            .id("data-structure-activity-status")
                            .label("menu.data.structure.activity_status")
                            .url("/data/structure/activity-status")
                            .icon("activity")
                            .permission("data.structure.view")
                            .active(true)
                            .order(5)
                            .build(),
                        MenuItem.builder()
                            .id("data-structure-belongs-to")
                            .label("menu.data.structure.belongs_to")
                            .url("/data/structure/belongs-to")
                            .icon("link")
                            .permission("data.structure.view")
                            .active(true)
                            .order(6)
                            .build()
                    ))
                    .build(),
                MenuItem.builder()
                    .id("data-employee")
                    .label("menu.data.employee")
                    .url("/data/employee")
                    .icon("users")
                    .permission("data.employee.view")
                    .active(true)
                    .order(3)
                    .items(Arrays.asList(
                        MenuItem.builder()
                            .id("data-employee-type")
                            .label("menu.data.employee.type")
                            .url("/data/employee/type")
                            .icon("user-check")
                            .permission("data.employee.view")
                            .active(true)
                            .order(1)
                            .build(),
                        MenuItem.builder()
                            .id("data-employee-status")
                            .label("menu.data.employee.status")
                            .url("/data/employee/status")
                            .icon("user-x")
                            .permission("data.employee.view")
                            .active(true)
                            .order(2)
                            .build(),
                        MenuItem.builder()
                            .id("data-employee-rate")
                            .label("menu.data.employee.rate")
                            .url("/data/employee/rate")
                            .icon("percent")
                            .permission("data.employee.view")
                            .active(true)
                            .order(3)
                            .build(),
                        MenuItem.builder()
                            .id("data-employee-form")
                            .label("menu.data.employee.form")
                            .url("/data/employee/form")
                            .icon("file-text")
                            .permission("data.employee.view")
                            .active(true)
                            .order(4)
                            .build(),
                        MenuItem.builder()
                            .id("data-employee-position-type")
                            .label("menu.data.employee.position_type")
                            .url("/data/employee/position-type")
                            .icon("briefcase")
                            .permission("data.employee.view")
                            .active(true)
                            .order(5)
                            .build(),
                        MenuItem.builder()
                            .id("data-employee-qualification")
                            .label("menu.data.employee.qualification")
                            .url("/data/employee/qualification")
                            .icon("award")
                            .permission("data.employee.view")
                            .active(true)
                            .order(6)
                            .build(),
                        MenuItem.builder()
                            .id("data-employee-achievement")
                            .label("menu.data.employee.achievement")
                            .url("/data/employee/achievement")
                            .icon("star")
                            .permission("data.employee.view")
                            .active(true)
                            .order(7)
                            .build(),
                        MenuItem.builder()
                            .id("data-employee-degree")
                            .label("menu.data.employee.degree")
                            .url("/data/employee/degree")
                            .icon("graduation-cap")
                            .permission("data.employee.view")
                            .active(true)
                            .order(8)
                            .build(),
                        MenuItem.builder()
                            .id("data-employee-rank")
                            .label("menu.data.employee.rank")
                            .url("/data/employee/rank")
                            .icon("trending-up")
                            .permission("data.employee.view")
                            .active(true)
                            .order(9)
                            .build()
                    ))
                    .build(),
                MenuItem.builder()
                    .id("data-student")
                    .label("menu.data.student")
                    .url("/data/student")
                    .icon("user-circle")
                    .permission("data.student.view")
                    .active(true)
                    .order(4)
                    .items(Arrays.asList(
                        MenuItem.builder()
                            .id("data-student-status")
                            .label("menu.data.student.status")
                            .url("/data/student/status")
                            .icon("circle")
                            .permission("data.student.view")
                            .active(true)
                            .order(1)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-achievement")
                            .label("menu.data.student.achievement")
                            .url("/data/student/achievement")
                            .icon("award")
                            .permission("data.student.view")
                            .active(true)
                            .order(2)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-expel")
                            .label("menu.data.student.expel")
                            .url("/data/student/expel")
                            .icon("user-minus")
                            .permission("data.student.view")
                            .active(true)
                            .order(3)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-accomodation")
                            .label("menu.data.student.accomodation")
                            .url("/data/student/accomodation")
                            .icon("home")
                            .permission("data.student.view")
                            .active(true)
                            .order(4)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-doctoral-type")
                            .label("menu.data.student.doctoral_type")
                            .url("/data/student/doctoral-type")
                            .icon("user-graduate")
                            .permission("data.student.view")
                            .active(true)
                            .order(5)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-social-type")
                            .label("menu.data.student.social_type")
                            .url("/data/student/social-type")
                            .icon("users")
                            .permission("data.student.view")
                            .active(true)
                            .order(6)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-academic-reason")
                            .label("menu.data.student.academic_reason")
                            .url("/data/student/academic-reason")
                            .icon("file-text")
                            .permission("data.student.view")
                            .active(true)
                            .order(7)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-doctoral-status")
                            .label("menu.data.student.doctoral_status")
                            .url("/data/student/doctoral-status")
                            .icon("check-circle")
                            .permission("data.student.view")
                            .active(true)
                            .order(8)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-graduate-fields")
                            .label("menu.data.student.graduate_fields")
                            .url("/data/student/graduate-fields")
                            .icon("briefcase")
                            .permission("data.student.view")
                            .active(true)
                            .order(9)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-graduate-inactive")
                            .label("menu.data.student.graduate_inactive")
                            .url("/data/student/graduate-inactive")
                            .icon("user-x")
                            .permission("data.student.view")
                            .active(true)
                            .order(10)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-type")
                            .label("menu.data.student.type")
                            .url("/data/student/type")
                            .icon("tag")
                            .permission("data.student.view")
                            .active(true)
                            .order(11)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-living-status")
                            .label("menu.data.student.living_status")
                            .url("/data/student/living-status")
                            .icon("home")
                            .permission("data.student.view")
                            .active(true)
                            .order(12)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-roommate-type")
                            .label("menu.data.student.roommate_type")
                            .url("/data/student/roommate-type")
                            .icon("users")
                            .permission("data.student.view")
                            .active(true)
                            .order(13)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-workplace-compatibility")
                            .label("menu.data.student.workplace_compatibility")
                            .url("/data/student/workplace-compatibility")
                            .icon("check-square")
                            .permission("data.student.view")
                            .active(true)
                            .order(14)
                            .build(),
                        MenuItem.builder()
                            .id("data-student-academic-mobile")
                            .label("menu.data.student.academic_mobile")
                            .url("/data/student/academic-mobile")
                            .icon("globe")
                            .permission("data.student.view")
                            .active(true)
                            .order(15)
                            .build()
                    ))
                    .build(),
                MenuItem.builder()
                    .id("data-education")
                    .label("menu.data.education")
                    .url("/data/education")
                    .icon("book")
                    .permission("data.education.view")
                    .active(true)
                    .order(5)
                    .items(Arrays.asList(
                        MenuItem.builder()
                            .id("data-education-type")
                            .label("menu.data.education.education_type")
                            .url("/data/education/type")
                            .icon("book-open")
                            .permission("data.education.view")
                            .active(true)
                            .order(1)
                            .build(),
                        MenuItem.builder()
                            .id("data-education-form")
                            .label("menu.data.education.education_form")
                            .url("/data/education/form")
                            .icon("book-open")
                            .permission("data.education.view")
                            .active(true)
                            .order(2)
                            .build(),
                        MenuItem.builder()
                            .id("data-education-language")
                            .label("menu.data.education.education_language")
                            .url("/data/education/language")
                            .icon("languages")
                            .permission("data.education.view")
                            .active(true)
                            .order(3)
                            .build(),
                        MenuItem.builder()
                            .id("data-education-grade-system")
                            .label("menu.data.education.grade_system_type")
                            .url("/data/education/grade-system")
                            .icon("award")
                            .permission("data.education.view")
                            .active(true)
                            .order(4)
                            .build(),
                        MenuItem.builder()
                            .id("data-education-score-type")
                            .label("menu.data.education.score_type")
                            .url("/data/education/score-type")
                            .icon("star")
                            .permission("data.education.view")
                            .active(true)
                            .order(5)
                            .build(),
                        MenuItem.builder()
                            .id("data-education-exam-type")
                            .label("menu.data.education.exam_type")
                            .url("/data/education/exam-type")
                            .icon("clipboard")
                            .permission("data.education.view")
                            .active(true)
                            .order(6)
                            .build(),
                        MenuItem.builder()
                            .id("data-education-diploma-blank-category")
                            .label("menu.data.education.diploma_blank_category")
                            .url("/data/education/diploma-blank-category")
                            .icon("file-text")
                            .permission("data.education.view")
                            .active(true)
                            .order(7)
                            .build(),
                        MenuItem.builder()
                            .id("data-education-diploma-blank-status")
                            .label("menu.data.education.diploma_blank_status")
                            .url("/data/education/diploma-blank-status")
                            .icon("file-check")
                            .permission("data.education.view")
                            .active(true)
                            .order(8)
                            .build(),
                        MenuItem.builder()
                            .id("data-education-diploma-blank-generate")
                            .label("menu.data.education.diploma_blank_generate_status")
                            .url("/data/education/diploma-blank-generate")
                            .icon("file-plus")
                            .permission("data.education.view")
                            .active(true)
                            .order(9)
                            .build(),
                        MenuItem.builder()
                            .id("data-education-certificate-type")
                            .label("menu.data.education.certificate_type")
                            .url("/data/education/certificate-type")
                            .icon("award")
                            .permission("data.education.view")
                            .active(true)
                            .order(10)
                            .build(),
                        MenuItem.builder()
                            .id("data-education-certificate-names")
                            .label("menu.data.education.certificate_names")
                            .url("/data/education/certificate-names")
                            .icon("award")
                            .permission("data.education.view")
                            .active(true)
                            .order(11)
                            .build(),
                        MenuItem.builder()
                            .id("data-education-certificate-subjects")
                            .label("menu.data.education.certificate_subjects")
                            .url("/data/education/certificate-subjects")
                            .icon("book")
                            .permission("data.education.view")
                            .active(true)
                            .order(12)
                            .build(),
                        MenuItem.builder()
                            .id("data-education-certificate-grades")
                            .label("menu.data.education.certificate_grades")
                            .url("/data/education/certificate-grades")
                            .icon("star")
                            .permission("data.education.view")
                            .active(true)
                            .order(13)
                            .build()
                    ))
                    .build(),
                MenuItem.builder()
                    .id("data-study")
                    .label("menu.data.study")
                    .url("/data/study")
                    .icon("edit")
                    .permission("data.study.view")
                    .active(true)
                    .order(6)
                    .items(Arrays.asList(
                        MenuItem.builder().id("data-study-year").label("menu.data.study.year").url("/data/study/year").icon("calendar").permission("data.study.view").active(true).order(1).build(),
                        MenuItem.builder().id("data-study-course").label("menu.data.study.course").url("/data/study/course").icon("book-open").permission("data.study.view").active(true).order(2).build(),
                        MenuItem.builder().id("data-study-semester").label("menu.data.study.semester").url("/data/study/semester").icon("calendar-days").permission("data.study.view").active(true).order(3).build(),
                        MenuItem.builder().id("data-study-week-type").label("menu.data.study.week_type").url("/data/study/week-type").icon("calendar-range").permission("data.study.view").active(true).order(4).build(),
                        MenuItem.builder().id("data-study-subject-block").label("menu.data.study.subject_block").url("/data/study/subject-block").icon("grid-3x3").permission("data.study.view").active(true).order(5).build(),
                        MenuItem.builder().id("data-study-subject-type").label("menu.data.study.subject_type").url("/data/study/subject-type").icon("list").permission("data.study.view").active(true).order(6).build(),
                        MenuItem.builder().id("data-study-class-type").label("menu.data.study.class_type").url("/data/study/class-type").icon("presentation").permission("data.study.view").active(true).order(7).build(),
                        MenuItem.builder().id("data-study-exam-finish").label("menu.data.study.exam_finish").url("/data/study/exam-finish").icon("check-circle").permission("data.study.view").active(true).order(8).build(),
                        MenuItem.builder().id("data-study-final-exam-type").label("menu.data.study.final_exam_type").url("/data/study/final-exam-type").icon("clipboard-check").permission("data.study.view").active(true).order(9).build(),
                        MenuItem.builder().id("data-study-semester-list").label("menu.data.study.semester_list").url("/data/study/semester-list").icon("list-ordered").permission("data.study.view").active(true).order(10).build(),
                        MenuItem.builder().id("data-study-decree-type").label("menu.data.study.decree_type").url("/data/study/decree-type").icon("file-text").permission("data.study.view").active(true).order(11).build(),
                        MenuItem.builder().id("data-study-sport-type").label("menu.data.study.sport_type").url("/data/study/sport-type").icon("trophy").permission("data.study.view").active(true).order(12).build(),
                        MenuItem.builder().id("data-study-attendance-setting").label("menu.data.study.attendance_setting").url("/data/study/attendance-setting").icon("settings").permission("data.study.view").active(true).order(13).build(),
                        MenuItem.builder().id("data-study-conduction-form").label("menu.data.study.conduction_form").url("/data/study/conduction-form").icon("presentation").permission("data.study.view").active(true).order(14).build(),
                        MenuItem.builder().id("data-study-internship-form").label("menu.data.study.internship_form").url("/data/study/internship-form").icon("briefcase").permission("data.study.view").active(true).order(15).build(),
                        MenuItem.builder().id("data-study-internship-type").label("menu.data.study.internship_type").url("/data/study/internship-type").icon("briefcase").permission("data.study.view").active(true).order(16).build(),
                        MenuItem.builder().id("data-study-resource-type").label("menu.data.study.resource_type").url("/data/study/resource-type").icon("package").permission("data.study.view").active(true).order(17).build(),
                        MenuItem.builder().id("data-study-outside-activities").label("menu.data.study.outside_activities").url("/data/study/outside-activities").icon("map-pin").permission("data.study.view").active(true).order(18).build()
                    ))
                    .build(),
                MenuItem.builder()
                    .id("data-science")
                    .label("menu.data.science")
                    .url("/data/science")
                    .icon("graduation-cap")
                    .permission("data.science.view")
                    .active(true)
                    .order(7)
                    .items(Arrays.asList(
                        MenuItem.builder().id("data-science-project-type").label("menu.data.science.project_type").url("/data/science/project-type").icon("flask").permission("data.science.view").active(true).order(1).build(),
                        MenuItem.builder().id("data-science-project-locality").label("menu.data.science.project_locality").url("/data/science/project-locality").icon("map").permission("data.science.view").active(true).order(2).build(),
                        MenuItem.builder().id("data-science-currency").label("menu.data.science.currency").url("/data/science/currency").icon("dollar-sign").permission("data.science.view").active(true).order(3).build(),
                        MenuItem.builder().id("data-science-executor-type").label("menu.data.science.executor_type").url("/data/science/executor-type").icon("users").permission("data.science.view").active(true).order(4).build(),
                        MenuItem.builder().id("data-science-publication-type").label("menu.data.science.publication_type").url("/data/science/publication-type").icon("book").permission("data.science.view").active(true).order(5).build(),
                        MenuItem.builder().id("data-science-methodical-type").label("menu.data.science.methodical_type").url("/data/science/methodical-type").icon("book-open").permission("data.science.view").active(true).order(6).build(),
                        MenuItem.builder().id("data-science-patent-type").label("menu.data.science.patent_type").url("/data/science/patent-type").icon("file-badge").permission("data.science.view").active(true).order(7).build(),
                        MenuItem.builder().id("data-science-publication-database").label("menu.data.science.publication_database").url("/data/science/publication-database").icon("database").permission("data.science.view").active(true).order(8).build(),
                        MenuItem.builder().id("data-science-scholar-database").label("menu.data.science.scholar_database").url("/data/science/scholar-database").icon("database").permission("data.science.view").active(true).order(9).build()
                    ))
                    .build(),
                MenuItem.builder()
                    .id("data-organizational")
                    .label("menu.data.organizational")
                    .url("/data/organizational")
                    .icon("building-2")
                    .permission("data.organizational.view")
                    .active(true)
                    .order(8)
                    .items(Arrays.asList(
                        MenuItem.builder().id("data-organizational-payment-form").label("menu.data.organizational.payment_form").url("/data/organizational/payment-form").icon("credit-card").permission("data.organizational.view").active(true).order(1).build(),
                        MenuItem.builder().id("data-organizational-stipend-rate").label("menu.data.organizational.stipend_rate").url("/data/organizational/stipend-rate").icon("banknote").permission("data.organizational.view").active(true).order(2).build(),
                        MenuItem.builder().id("data-organizational-stipend-category").label("menu.data.organizational.stipend_category").url("/data/organizational/stipend-category").icon("tag").permission("data.organizational.view").active(true).order(3).build(),
                        MenuItem.builder().id("data-organizational-scholarship-decree").label("menu.data.organizational.scholarship_decree").url("/data/organizational/scholarship-decree").icon("file-text").permission("data.organizational.view").active(true).order(4).build(),
                        MenuItem.builder().id("data-organizational-contract-type").label("menu.data.organizational.contract_type").url("/data/organizational/contract-type").icon("file-contract").permission("data.organizational.view").active(true).order(5).build(),
                        MenuItem.builder().id("data-organizational-contract-summa").label("menu.data.organizational.contract_summa").url("/data/organizational/contract-summa").icon("dollar-sign").permission("data.organizational.view").active(true).order(6).build(),
                        MenuItem.builder().id("data-organizational-contract-types").label("menu.data.organizational.contract_types").url("/data/organizational/contract-types").icon("list").permission("data.organizational.view").active(true).order(7).build(),
                        MenuItem.builder().id("data-organizational-auditorium-type").label("menu.data.organizational.auditorium_type").url("/data/organizational/auditorium-type").icon("door-closed").permission("data.organizational.view").active(true).order(8).build(),
                        MenuItem.builder().id("data-organizational-device-type").label("menu.data.organizational.device_type").url("/data/organizational/device-type").icon("monitor").permission("data.organizational.view").active(true).order(9).build(),
                        MenuItem.builder().id("data-organizational-grant-type").label("menu.data.organizational.grant_type").url("/data/organizational/grant-type").icon("gift").permission("data.organizational.view").active(true).order(10).build()
                    ))
                    .build(),
                MenuItem.builder()
                    .id("data-contract-category")
                    .label("menu.data.contract_category")
                    .url("/data/contract-category")
                    .icon("file-signature")
                    .permission("data.contract-category.view")
                    .active(true)
                    .order(9)
                    .build()
            ))
            .build();
    }

    /**
     * Reports Menu
     */
    private MenuItem createReports() {
        return MenuItem.builder()
            .id("reports")
            .label("menu.reports")
            .url("/reports")
            .icon("bar-chart")
            .permission("reports.view")
            .active(true)
            .order(5)
            .items(Arrays.asList(
                // Universities Reports
                MenuItem.builder()
                    .id("reports-universities")
                    .label("menu.reports.universities")
                    .url("/reports/universities")
                    .icon("building")
                    .permission("reports.universities.view")
                    .active(true)
                    .order(1)
                    .items(Arrays.asList(
                        MenuItem.builder().id("reports-universities-count").label("menu.reports.universities.count").url("/reports/universities/count").icon("hash").permission("reports.universities.view").active(true).order(1).build(),
                        MenuItem.builder().id("reports-universities-faculty-list").label("menu.reports.universities.faculty_list").url("/reports/universities/faculty-list").icon("list").permission("reports.universities.view").active(true).order(2).build()
                    ))
                    .build(),

                // Employees Reports
                MenuItem.builder()
                    .id("reports-employees")
                    .label("menu.reports.employees")
                    .url("/reports/employees")
                    .icon("users")
                    .permission("reports.employees.view")
                    .active(true)
                    .order(2)
                    .items(Arrays.asList(
                        MenuItem.builder()
                            .id("reports-employees-navigation")
                            .label("menu.reports.employees.navigation")
                            .url("/reports/employees/navigation")
                            .icon("line-chart")
                            .permission("reports.employees.view")
                            .active(true)
                            .order(1)
                            .build(),
                        MenuItem.builder()
                            .id("reports-employees-private")
                            .label("menu.reports.employees.private")
                            .url("/reports/employees/private")
                            .icon("line-chart")
                            .permission("reports.employees.private.view")
                            .active(true)
                            .order(2)
                            .build(),
                        MenuItem.builder()
                            .id("reports-employees-work")
                            .label("menu.reports.employees.work")
                            .url("/reports/employees/work")
                            .icon("line-chart")
                            .permission("reports.employees.work.view")
                            .active(true)
                            .order(3)
                            .build()
                    ))
                    .build(),

                // Students Reports
                MenuItem.builder()
                    .id("reports-students")
                    .label("menu.reports.students")
                    .url("/reports/students")
                    .icon("graduation-cap")
                    .permission("reports.students.view")
                    .active(true)
                    .order(3)
                    .items(Arrays.asList(
                        MenuItem.builder()
                            .id("reports-students-statistics")
                            .label("menu.reports.students.statistics")
                            .url("/reports/students/statistics")
                            .icon("line-chart")
                            .permission("reports.students.statistics.view")
                            .active(true)
                            .order(1)
                            .build(),
                        MenuItem.builder()
                            .id("reports-students-education")
                            .label("menu.reports.students.education")
                            .url("/reports/students/education")
                            .icon("bar-chart")
                            .permission("reports.students.education.view")
                            .active(true)
                            .order(2)
                            .build(),
                        MenuItem.builder()
                            .id("reports-students-private")
                            .label("menu.reports.students.private")
                            .url("/reports/students/private")
                            .icon("bar-chart")
                            .permission("reports.students.private.view")
                            .active(true)
                            .order(3)
                            .build(),
                        MenuItem.builder()
                            .id("reports-students-attendance")
                            .label("menu.reports.students.attendance")
                            .url("/reports/students/attendance")
                            .icon("bar-chart")
                            .permission("reports.students.attendance.view")
                            .active(true)
                            .order(4)
                            .build(),
                        MenuItem.builder()
                            .id("reports-students-score")
                            .label("menu.reports.students.score")
                            .url("/reports/students/score")
                            .icon("bar-chart")
                            .permission("reports.students.score.view")
                            .active(true)
                            .order(5)
                            .build(),
                        MenuItem.builder()
                            .id("reports-students-dynamic")
                            .label("menu.reports.students.dynamic")
                            .url("/reports/students/dynamic")
                            .icon("pie-chart")
                            .permission("reports.students.dynamic.view")
                            .active(true)
                            .order(6)
                            .build()
                    ))
                    .build(),

                // Academic Reports
                MenuItem.builder()
                    .id("reports-academic")
                    .label("menu.reports.academic")
                    .url("/reports/academic")
                    .icon("book")
                    .permission("reports.academic.view")
                    .active(true)
                    .order(4)
                    .items(Arrays.asList(
                        MenuItem.builder()
                            .id("reports-academic-study")
                            .label("menu.reports.academic.study")
                            .url("/reports/academic/study")
                            .icon("pie-chart")
                            .permission("reports.academic.study.view")
                            .active(true)
                            .order(1)
                            .build()
                    ))
                    .build(),

                // Research Reports
                MenuItem.builder()
                    .id("reports-research")
                    .label("menu.reports.research")
                    .url("/reports/research")
                    .icon("flask")
                    .permission("reports.research.view")
                    .active(true)
                    .order(5)
                    .items(Arrays.asList(
                        MenuItem.builder()
                            .id("reports-research-project")
                            .label("menu.reports.research.project")
                            .url("/reports/research/project")
                            .icon("pie-chart")
                            .permission("reports.research.project.view")
                            .active(true)
                            .order(1)
                            .build(),
                        MenuItem.builder()
                            .id("reports-research-publication")
                            .label("menu.reports.research.publication")
                            .url("/reports/research/publication")
                            .icon("pie-chart")
                            .permission("reports.research.publication.view")
                            .active(true)
                            .order(2)
                            .build(),
                        MenuItem.builder()
                            .id("reports-research-researcher")
                            .label("menu.reports.research.researcher")
                            .url("/reports/research/researcher")
                            .icon("pie-chart")
                            .permission("reports.research.researcher.view")
                            .active(true)
                            .order(3)
                            .build()
                    ))
                    .build(),

                // Economic Reports
                MenuItem.builder()
                    .id("reports-economic")
                    .label("menu.reports.economic")
                    .url("/reports/economic")
                    .icon("banknote")
                    .permission("reports.economic.view")
                    .active(true)
                    .order(6)
                    .items(Arrays.asList(
                        MenuItem.builder()
                            .id("reports-economic-finance")
                            .label("menu.reports.economic.finance")
                            .url("/reports/economic/finance")
                            .icon("bar-chart")
                            .permission("reports.economic.finance.view")
                            .active(true)
                            .order(1)
                            .build(),
                        MenuItem.builder()
                            .id("reports-economic-xujalik")
                            .label("menu.reports.economic.xujalik")
                            .url("/reports/economic/xujalik")
                            .icon("bar-chart")
                            .permission("reports.economic.xujalik.view")
                            .active(true)
                            .order(2)
                            .build()
                    ))
                    .build()
            ))
            .build();
    }

    /**
     * System Menu
     */
    private MenuItem createSystem() {
        return MenuItem.builder()
            .id("system")
            .label("menu.system")
            .url("/system")
            .icon("settings")
            .permission("system.view")
            .active(true)
            .order(6)
            .items(Arrays.asList(
                MenuItem.builder()
                    .id("system-temp")
                    .label("menu.system.temp")
                    .url("/system/temp")
                    .icon("settings")
                    .permission("system.temp.view")
                    .active(true)
                    .order(1)
                    .build(),
                MenuItem.builder()
                    .id("system-translation")
                    .label("menu.system.translation")
                    .url("/system/translation")
                    .icon("languages")
                    .permission("system.translation.view")
                    .active(true)
                    .order(2)
                    .build(),
                MenuItem.builder()
                    .id("system-university-users")
                    .label("menu.system.university_users")
                    .url("/system/university-users")
                    .icon("users")
                    .permission("system.users.view")
                    .active(true)
                    .order(3)
                    .build(),
                MenuItem.builder()
                    .id("system-api-logs")
                    .label("menu.system.api_logs")
                    .url("/system/api-logs")
                    .icon("file-text")
                    .permission("system.logs.view")
                    .active(true)
                    .order(4)
                    .build(),
                MenuItem.builder()
                    .id("system-report-update")
                    .label("menu.system.report_update")
                    .url("/system/report-update")
                    .icon("refresh-cw")
                    .permission("system.report-update.view")
                    .active(true)
                    .order(5)
                    .build()
            ))
            .build();
    }
}
